import { query } from '../db.js';

// Every detecting agent already computes expected_impact.value — real
// impressions/clicks/gap-magnitude at finding time (see
// server/agents/*.js's expectedImpact literals) — but until now nothing
// read it back: both open-recommendation queries below ordered purely by
// priority tier + recency, discarding the one number that says which
// same-tier finding is actually worth more. Generic across every site: no
// client-specific weighting, just "prefer the bigger number this agent
// already measured, within the same priority tier".
//
// Guarded by a regex rather than a bare ::numeric cast — expected_impact is
// free-form JSONB written by ~20 different agents, and one future non-numeric
// value would otherwise throw inside the ORDER BY and break the ship queue
// for every site, not just the row that produced it. NULLS LAST (via
// DESC NULLS LAST at each call site) so a finding with basis:'estimate' and
// no value falls back to priority-tier + recency exactly as before.
const IMPACT_VALUE_SQL = `(CASE WHEN expected_impact->>'value' ~ '^-?[0-9]+(\\.[0-9]+)?$'
                                THEN (expected_impact->>'value')::numeric END)`;

// CRUD for the recommendations table — the Recommendation Coordinator's only
// persistence layer (see agents/lib/recommendation-coordinator.js, which is
// the only caller allowed to invoke the writes below). Dedup key is
// (site_id, page, recommendation_type); the DB enforces it via
// recommendations_dedup_key (migration 077), these helpers just implement
// the read-before-write merge on top of it.

// Turns a blocked_reason's TEXT into the Action Center's three-way
// classification (migration 110) — the difference between "you need to do
// something", "nothing to do, wait", and "this is how the site is built, not
// a gap". blocked_reason is written for a human to read; blocked_kind is
// written for the UI to branch on, so the wording of blocked_reason can keep
// evolving without also having to touch every UI conditional that used to
// pattern-match on it directly.
//
// Order matters: checked most-specific first. A message can plausibly match
// more than one pattern (e.g. a config-gap message mentioning "queued" for
// an unrelated reason), so the first real match wins rather than the most
// recently added one.
export function classifyBlockedKind(blockedReason) {
  if (!blockedReason) return null;
  // "shared CSS class"/"shared stylesheet" added 2026-09-03 for
  // font-consistency's report-only outliers: an element whose font-size is
  // wrong because a SHARED class says so is the same category of thing as a
  // shared template — real, worth seeing, and not something a per-page fix
  // can safely change, since editing the class moves every other element
  // using it too. Same 'site-fact' framing, same "Can't be drafted here" UI.
  if (/generated by .+ one per item|shared (template|layout|css class|stylesheet)/i.test(blockedReason)) return 'site-fact';
  // "currently running" added alongside "queued" (implementers/lib/
  // design-agent-status.js, 2026-08-24): a job actively executing is exactly
  // as much "nothing to click, already in progress" as one still queued —
  // without this, an in-flight job read as 'our-config' ("Blocked — setup
  // needed"), which is not what a live run is.
  if (/queued|currently running|hasn't been derived|has never been verified/i.test(blockedReason)) return 'awaiting-derivation';
  // A failed Design Context analysis (implementers/lib/design-agent-status.js's
  // FAILED state) never stops drafting — the message itself says drafts fall
  // back to the default template and retry automatically — so it must not
  // wear 'our-config''s "Blocked — setup needed" framing, which promises the
  // opposite. Kept distinct from 'awaiting-derivation' (migration 128) rather
  // than merged into it: a repeated failure is still worth a human being able
  // to see, unlike routine queued/running progress.
  if (/drafts (continue|use) .*fallback template|will retry automatically/i.test(blockedReason)) return 'design-degraded';
  return 'our-config';
}

export async function findOpenRecommendation(siteId, page, recommendationType) {
  const { rows } = await query(
    `SELECT * FROM recommendations WHERE site_id = $1 AND page = $2 AND recommendation_type = $3 AND status = 'open'`,
    [siteId, page, recommendationType]
  );
  return rows[0] || null;
}

export async function insertRecommendation(siteId, {
  page, recommendationType, issue, reason, params, findingId, detectingAgent, priority, expectedImpact, riskTier,
  blockedReason, confidence,
}) {
  const { rows } = await query(
    `INSERT INTO recommendations
       (site_id, page, recommendation_type, issue, reason, params, finding_ids, detecting_agents, priority, expected_impact, risk_tier, blocked_reason, blocked_kind, blocked_since, confidence)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, CASE WHEN $12::text IS NOT NULL THEN now() ELSE NULL END, $14)
     RETURNING *`,
    [
      siteId, page, recommendationType, issue, reason || null, JSON.stringify(params || {}),
      [findingId], [detectingAgent], priority || 'medium', expectedImpact ? JSON.stringify(expectedImpact) : null,
      riskTier || 'manual', blockedReason ?? null, classifyBlockedKind(blockedReason),
      confidence ?? null,
    ]
  );
  return rows[0];
}

// Merges a fresh grounded finding into an already-open recommendation row:
// adds the finding id, and adds the agent to supporting_agents unless it's
// already the original detector or already recorded; refreshes the evidence
// fields to the latest sync's values. detecting_agents is set once at
// insertRecommendation and never mutated here — it's "who found it first,"
// supporting_agents is "who else corroborated it." Never changes `status` —
// closing a recommendation is out of scope for M1 (see
// recommendation-coordinator.js's syncFromGrounded doc comment).
export async function mergeIntoRecommendation(id, { findingId, agentId, reason, params, priority, expectedImpact, blockedReason, riskTier, confidence }) {
  // risk_tier is NOT NULL and is now written unconditionally, so an omitted
  // riskTier would surface as a constraint violation deep in the driver.
  // Reject it here instead, where the caller is still in the stack trace.
  if (!riskTier) throw new Error('mergeIntoRecommendation requires riskTier (use blockedRiskTier)');
  const { rows } = await query(
    `UPDATE recommendations SET
       finding_ids = (SELECT ARRAY(SELECT DISTINCT unnest(finding_ids || $2::text[]))),
       supporting_agents = CASE
         WHEN $3 = ANY(detecting_agents) OR $3 = ANY(supporting_agents) THEN supporting_agents
         ELSE supporting_agents || $3::text
       END,
       reason = COALESCE($4, reason),
       params = COALESCE($5, params),
       priority = COALESCE($6, priority),
       expected_impact = COALESCE($7, expected_impact),
       -- Refreshed to the latest sync's value like expected_impact above (a
       -- forecast_risk insight's confidence moves run to run) — COALESCE so a
       -- merge from a caller that doesn't compute confidence (e.g. keyword
       -- gaps, which have no honest confidence signal) never blanks out a
       -- value a forecast-based sync already set.
       confidence = COALESCE($11, confidence),
       -- Deliberately NOT COALESCE: these two must be able to go back to
       -- NULL/'safe' when whatever was blocking clears — a component template
       -- gets verified, or a url_file_map entry finally resolves (possibly via
       -- autoHealFileMapping, with no human involved at all). COALESCE would
       -- make a block permanent once set, so a site that fixed the underlying
       -- cause would stay stuck in the manual tier forever. Both are recomputed
       -- from live state on every sync by recommendation-coordinator.js's
       -- blockedRiskTier, so overwriting unconditionally is the correct
       -- semantics here.
       --
       -- risk_tier was COALESCE'd here until 2026-08-13, which meant a caller
       -- passing a falsy riskTier alongside a fresh blocked_reason would leave
       -- a stale 'safe' next to a live block — the exact contradiction
       -- migration 108 now forbids at the DB level. The two fields express one
       -- decision (blockedRiskTier), so they are written as one.
       blocked_reason = $8,
       blocked_kind = $9,
       -- blocked_since: set on the transition into a block, cleared on the
       -- transition out, left untouched while it stays blocked. References
       -- blocked_reason's PRE-update value — Postgres resolves every column
       -- reference in an UPDATE's SET list against the row as it was before
       -- this statement, regardless of assignment order.
       blocked_since = CASE
         WHEN $8::text IS NOT NULL AND blocked_reason IS NULL THEN now()
         WHEN $8::text IS NULL THEN NULL
         ELSE blocked_since
       END,
       risk_tier = $10,
       last_seen_at = now(),
       updated_at = now()
     WHERE id = $1
     RETURNING *`,
    [
      id, [findingId], agentId, reason || null,
      params ? JSON.stringify(params) : null, priority || null,
      expectedImpact ? JSON.stringify(expectedImpact) : null,
      blockedReason ?? null, classifyBlockedKind(blockedReason), riskTier,
      confidence ?? null,
    ]
  );
  return rows[0];
}

// Refreshes ONLY the block state of an already-open recommendation, without
// touching finding_ids/supporting_agents/evidence.
//
// syncFromGrounded skips the full merge when a finding id is already on the
// row (deterministic finding ids mean a re-detected finding is the same id
// every run, so re-merging it would be pure churn). But block state is not
// part of the finding — it is recomputed from live site/repo state on every
// sync, and skipping the merge was also skipping that recomputation. The
// result: a block that cleared never cleared, and a block that appeared never
// appeared, on any recommendation the agents keep re-detecting. That is what
// let migration 078's corruption survive indefinitely instead of being
// overwritten by the next sync.
//
// last_seen_at is bumped because we did re-detect the finding this run — the
// staleness sweep in closeStaleRecommendations reads it.
export async function refreshRecommendationBlockState(id, { blockedReason, riskTier }) {
  if (!riskTier) throw new Error('refreshRecommendationBlockState requires riskTier (use blockedRiskTier)');
  const { rows } = await query(
    `UPDATE recommendations SET
       blocked_reason = $2,
       blocked_kind = $4,
       blocked_since = CASE
         WHEN $2::text IS NOT NULL AND blocked_reason IS NULL THEN now()
         WHEN $2::text IS NULL THEN NULL
         ELSE blocked_since
       END,
       risk_tier = $3,
       last_seen_at = now(),
       updated_at = now()
     WHERE id = $1
       AND (blocked_reason IS DISTINCT FROM $2 OR risk_tier IS DISTINCT FROM $3)
     RETURNING *`,
    [id, blockedReason ?? null, riskTier, classifyBlockedKind(blockedReason)]
  );
  return rows[0] || null; // null = already correct, nothing written
}

// Every currently-open, currently-blocked row, optionally scoped to who
// detected it. Used by recommendation-coordinator.js's
// refreshBlockedRecommendations to periodically re-validate blockers against
// live state — the daily pass excludes 'analyst-keyword-gaps' rows (content
// gaps get their own slower weekly pass; see job.js), the weekly pass
// includes only them. Never touches status, so a row this misses one run
// (transient API error) is simply re-checked next time, and a row that isn't
// open at all is invisible to it by construction.
export async function listOpenBlockedRecommendations(siteId, { onlyDetectingAgent, excludeDetectingAgent } = {}) {
  const { rows } = await query(
    `SELECT id, recommendation_type, params, detecting_agents FROM recommendations
     WHERE site_id = $1 AND status = 'open' AND blocked_reason IS NOT NULL
       AND ($2::text IS NULL OR $2 = ANY(detecting_agents))
       AND ($3::text IS NULL OR NOT ($3 = ANY(detecting_agents)))`,
    [siteId, onlyDetectingAgent || null, excludeDetectingAgent || null]
  );
  return rows;
}

export async function listOpenRecommendations(siteId) {
  const { rows } = await query(
    `SELECT * FROM recommendations WHERE site_id = $1 AND status = 'open' ORDER BY
       CASE priority WHEN 'high' THEN 0 WHEN 'medium' THEN 1 ELSE 2 END,
       ${IMPACT_VALUE_SQL} DESC NULLS LAST, last_seen_at DESC`,
    [siteId]
  );
  return rows;
}

export async function getRecommendationById(siteId, id) {
  const { rows } = await query('SELECT * FROM recommendations WHERE site_id = $1 AND id = $2', [siteId, id]);
  return rows[0] || null;
}

// Closes a single recommendation on demand — used by the manual "re-check
// now" action (recommendation-coordinator.js's recheckRecommendation), as
// opposed to closeStaleRecommendations' bulk sweep on every sync.
export async function closeRecommendation(id) {
  await query(`UPDATE recommendations SET status = 'superseded', updated_at = now() WHERE id = $1`, [id]);
}

// 'dismissed' has been a valid status since migration 077b/110, but until
// now nothing in this codebase ever wrote it — 'superseded' (a re-check no
// longer detecting the issue) and 'unfixable' (proven dead) were the only
// real close paths. Distinct from both: a human deciding a recommendation is
// not real/not worth acting on RIGHT NOW, without claiming the underlying
// finding resolved itself or is permanently impossible. Frees the dedup key
// the same way every other terminal status does (status != 'open'), so if
// the same page + type genuinely regresses later it opens a fresh row.
export async function dismissRecommendation(id) {
  await query(`UPDATE recommendations SET status = 'dismissed', updated_at = now() WHERE id = $1`, [id]);
}

// Puts an EXISTING recommendation back on the board after an attempt against
// it was reclaimed (lib/action-center-reconciler.js). Never inserts — that is
// the whole point. The alternative the reconciler must not take is letting
// detection re-raise the issue as a fresh row: that produces a second card
// for an issue the user has already seen, with an attempt history of zero,
// which is precisely the duplication this work exists to end.
//
// Clearing execution_job_id/execution_status matters as much as the status
// flip. listOpenSafeRecommendations excludes any row with a non-null
// execution_job_id so a recommendation already claimed by a job is never
// picked up twice — correct while the job is live, but a row whose job died
// stranded stays permanently invisible to the unattended path unless the
// claim is released here.
//
// Returns { reopened, conflictId }. A conflict is not an error: the partial
// unique index (recommendations_dedup_key, status='open') means another OPEN
// row already holds this exact (site, page, type) key — the issue is already
// represented by a live card, so leaving this one closed is the correct
// outcome and still satisfies one-issue-one-card. Reported rather than
// swallowed so the caller can log which row absorbed it.
export async function reopenRecommendation(id) {
  try {
    const { rows } = await query(
      `UPDATE recommendations
          SET status = 'open', execution_job_id = NULL, execution_status = NULL, updated_at = now()
        WHERE id = $1 AND status <> 'open'
        RETURNING *`,
      [id]
    );
    // No row updated means it was already open — the common case when an
    // attempt is reclaimed against a recommendation that was never closed.
    // Still a success: the card is on the board, which is all the caller
    // asked for. Release the execution claim regardless.
    if (!rows[0]) {
      await query(
        `UPDATE recommendations SET execution_job_id = NULL, execution_status = NULL, updated_at = now()
          WHERE id = $1 AND status = 'open'`,
        [id]
      );
    }
    return { reopened: true, conflictId: null };
  } catch (err) {
    if (err?.code !== '23505') throw err;
    const { rows } = await query(
      `SELECT r2.id FROM recommendations r1
         JOIN recommendations r2
           ON r2.site_id = r1.site_id AND r2.page = r1.page
          AND r2.recommendation_type = r1.recommendation_type
          AND r2.status = 'open' AND r2.id <> r1.id
        WHERE r1.id = $1`,
      [id]
    );
    return { reopened: false, conflictId: rows[0]?.id ?? null };
  }
}

// Marks an OPEN recommendation as waiting on a person, with the reason shown
// on the card. Used when an attempt fails with a NEEDS_HUMAN policy
// (lib/attempt-classification.js) — a missing url_file_map entry, an expired
// PAT. The row stays open and visible on purpose: an issue we detected but
// cannot currently fix must never silently vanish (that lesson is why
// blocked_reason exists at all — see migration 100).
//
// risk_tier is forced to 'manual' in the same statement, not as a separate
// call. Migration 108 makes a blocked row with risk_tier='safe' a CHECK
// violation, precisely because an unguarded backfill once re-promoted 45
// blocked rows into the unattended path on site 1.
export async function blockRecommendation(id, reason) {
  const { rows } = await query(
    `UPDATE recommendations
        SET blocked_reason = $2, blocked_kind = $3, risk_tier = 'manual',
            blocked_since = COALESCE(blocked_since, now()), updated_at = now()
      WHERE id = $1 AND status = 'open'
      RETURNING *`,
    [id, reason, classifyBlockedKind(reason)]
  );
  return rows[0] || null;
}

// risk_tier is not currently exposed on execution_job_id's caller, but every
// safe-tier recommendation not already claimed by an in-flight job is a
// candidate for executeSafeFixes (agents/lib/execution-engine.js) —
// excludes anything with a non-null execution_job_id so a recommendation
// already queued/shipped by an earlier job is never picked up twice.
//
// blocked_reason IS NULL is not redundant with risk_tier = 'safe', even
// though migration 108 now forbids a row from being both. Belt and braces on
// purpose: this is one of the two selectors that feed work into the
// unattended path (the other is auto-remediation.js's own filter), and the
// cost of the extra predicate is nil against the cost of shipping a
// known-unshippable recommendation if the invariant is ever weakened again.
// The last time this was reasoned about as "the tier already covers it", the
// tier stopped covering it and nobody noticed for weeks.
export async function listOpenSafeRecommendations(siteId, limit) {
  const { rows } = await query(
    `SELECT * FROM recommendations WHERE site_id = $1 AND status = 'open' AND risk_tier = 'safe' AND blocked_reason IS NULL AND execution_job_id IS NULL
       ORDER BY CASE priority WHEN 'high' THEN 0 WHEN 'medium' THEN 1 ELSE 2 END,
       ${IMPACT_VALUE_SQL} DESC NULLS LAST, last_seen_at DESC
       LIMIT $2`,
    [siteId, limit]
  );
  return rows;
}

// Marks a row 'unfixable' from DIRECT evidence gathered THIS run — a soft-404
// fingerprint match, a mapped file confirmed gone, adapter data confirmed
// never ready (recommendation-gates.js's `drop` outcomes). Deliberately
// bypasses closeStaleRecommendations' rotation-batch guard: that guard exists
// to tell "not re-checked today" apart from "genuinely resolved", which is
// the right caution for silence, but this is not silence — the page was
// looked at this run and proven unfixable. Withholding that conclusion until
// some later run's rotation happens to include this exact page is how a
// dropped-but-never-reported page stays open indefinitely (the immortal
// /docs/* rows on site 1: soft-404, dropped every run, never re-selected by
// batch rotation, so never closed).
//
// `unfixable` (not `superseded`) because superseded means "the underlying
// issue is resolved" — nothing was resolved here, the page simply cannot be
// fixed through this pipeline. Frees the dedup key exactly the same way
// (status != 'open'), so a page that reappears later opens a fresh row.
export async function markRecommendationsUnfixable(siteId, dropped) {
  let count = 0;
  for (const { generatorId, page, reason } of dropped) {
    // blocked_kind is left NULL here on purpose: it classifies WHY an OPEN
    // recommendation is blocked (our-config / awaiting-derivation / site-fact)
    // — an 'unfixable' row isn't blocked in that sense, it's terminal, and the
    // UI is expected to branch on status before ever looking at blocked_kind.
    // risk_tier must move to 'manual' in the same statement — migration 108's
    // recommendations_blocked_is_manual CHECK requires blocked_reason IS NULL
    // OR risk_tier = 'manual', and this row is about to get a blocked_reason.
    // Without it, any row whose risk_tier was 'safe' at the moment it became
    // unfixable throws here and aborts the REST of syncFromGrounded for this
    // site (closeStaleRecommendations et al. run first and are unaffected,
    // but nothing after this call in the same site's sync executes).
    const { rowCount } = await query(
      `UPDATE recommendations SET status = 'unfixable', blocked_reason = $4, risk_tier = 'manual', updated_at = now()
       WHERE site_id = $1 AND page = $2 AND recommendation_type = $3 AND status = 'open'`,
      [siteId, page, generatorId, reason || 'This page no longer exists or cannot be resolved to a real source.']
    );
    count += rowCount;
  }
  return count;
}

export async function setRecommendationExecutionState(id, { executionJobId, executionStatus }) {
  await query(
    'UPDATE recommendations SET execution_job_id = COALESCE($2, execution_job_id), execution_status = COALESCE($3, execution_status), updated_at = now() WHERE id = $1',
    [id, executionJobId ?? null, executionStatus ?? null]
  );
}

// Closes every currently-open row whose (recommendation_type, page) key is
// not in stillDetectedKeys — i.e. the agent that originally flagged it
// re-ran and no longer finds the issue. `superseded` (not `dismissed`,
// which means a human said "not relevant") and it frees the row's dedup
// key (recommendations_dedup_key is a partial unique index scoped to
// status = 'open'), so if the same page + type genuinely regresses later
// it opens a brand new row rather than being blocked by this closed one.
// Called once per site per sync from recommendation-coordinator.js's
// syncFromGrounded — see that file for how stillDetectedKeys is built.
//
// checked = { agentCheckedKeys, linkCrawlCheckedKeys, batchRotatedAgentIds,
// authoritativeAgentIds }, built by buildRecommendations (agents/lib/
// recommendations.js) and recommendation-coordinator.js's syncFromGrounded.
// authoritativeAgentIds is the roster this specific sync pass actually
// re-checks (RECOMMENDATION_AGENT_IDS, agents/lib/insights.js) — a row whose
// detecting_agents are ENTIRELY outside that roster (analyst-insights,
// analyst-keyword-gaps, growth-opportunities: sources with no detection step
// in THIS pass at all) is skipped outright, before any of the logic below
// runs. Most agents only examine a bounded rotation batch per run — a page
// missing from this run's findings usually means "not re-checked today," not
// "fixed," so closing on absence alone was making recommendations vanish in
// bulk (then often reappear later) without ever being confirmed clean. A
// stale row is only closed when we're sure it was actually re-verified:
//   - not this pass's business at all (see authoritativeAgentIds above): left untouched
//   - no page (site-level/collapsed key, e.g. cookie-policy, security-headers
//     as a fix action): unchanged — these are recomputed in full every run
//   - broken-link-fix: only if the page's outbound links were part of this
//     run's link crawl (narrower than its agent's own page batch — see
//     technical-seo-analysis.js)
//   - everything else: only if every agent that originally flagged it either
//     isn't rotation-batched (checks everything every run, so its silence is
//     already trustworthy) or did re-check this exact page this run
export async function closeStaleRecommendations(siteId, stillDetectedKeys, checked = {}) {
  const { agentCheckedKeys, linkCrawlCheckedKeys, batchRotatedAgentIds, authoritativeAgentIds } = checked;
  const { rows } = await query(
    `SELECT id, page, recommendation_type, detecting_agents FROM recommendations WHERE site_id = $1 AND status = 'open'`,
    [siteId]
  );
  const staleIds = rows
    .filter((r) => {
      const key = `${r.recommendation_type}::${r.page}`;
      if (stillDetectedKeys.has(key)) return false;
      // A row this call has no authority over — none of its detecting_agents
      // belong to the roster this sync pass actually re-checks (see
      // authoritativeAgentIds' own comment below) — must never be touched.
      // Confirmed real bug, fixed 2026-09-10: before this guard, a row whose
      // ONLY detecting_agent was e.g. 'analyst-insights' (never a member of
      // batchRotatedAgentIds, which only ever holds Node RECOMMENDATION_AGENT_IDS)
      // made the .every() check below vacuously true and got superseded on
      // the very next unrelated Node grounded-agent sync — same UTC morning
      // it was created, before the shipping pass ever saw it. Silence from a
      // detection pass that was never asked about this row's source in the
      // first place is not evidence the finding resolved.
      if (authoritativeAgentIds && !(r.detecting_agents || []).some((agentId) => authoritativeAgentIds.has(agentId))) return false;
      if (!r.page) return true;
      // r.page is recommendationPageKey()'s `${sourcePage}::${href}` compound for this
      // type (see recommendation-coordinator.js), but linkCrawlCheckedKeys holds bare
      // source-page URLs from this run's link crawl — compare against the source-page
      // half, not the whole compound key, or this branch can never match.
      if (r.recommendation_type === 'broken-link-fix') return !!linkCrawlCheckedKeys?.has(r.page.split('::')[0]);
      return (r.detecting_agents || []).every((agentId) => (
        !batchRotatedAgentIds?.has(agentId) || !!agentCheckedKeys?.has(`${agentId}::${r.page}`)
      ));
    })
    .map((r) => r.id);
  if (!staleIds.length) return 0;
  await query(
    `UPDATE recommendations SET status = 'superseded', updated_at = now() WHERE id = ANY($1::int[])`,
    [staleIds]
  );
  return staleIds.length;
}
