import { getBranchSha, createBranch, getFileSha, putFile, mergeBranch, openPullRequest } from '../../github/client.js';

// Company convention (~/Travel/ci-cd-deployment-master-guide): `stage` has
// no protection rules and auto-deploys on push/merge, so it's still the
// safe, cheap base every draft branch forks from and diffs against.
// Publishing a draft, though, now opens a real PR into `main` (see
// openPrForBranch below) instead of merging straight into `stage` — a human
// reviews and merges it on GitHub. Because the branch is forked from
// `stage` but the PR targets `main`, if a given client's `stage` has
// diverged from `main` (not promoted in a while), the PR diff will include
// that unrelated divergence too, not just this draft's change — that's
// intentional: it's surfaced to the human reviewer via the PR itself, which
// is the whole point of requiring manual review, not something this layer
// tries to rebase away. Exported so backend.js/frontend.js read the SAME
// real branch when fetching "current" content for a diff (preview) as
// pushDraftBranch actually forks from.
export const STAGE_BRANCH = 'stage';

// Two real, independently-triggered steps — deliberately NOT bundled. Staff
// needs a real manual checkpoint between "a branch with the real change
// exists" and "it's merged into stage (and therefore deployed)," so they
// can review the real pushed diff (dashboard's Draft Preview panel) first.
// Branch name is deterministic so a retried push targets the same branch
// instead of piling up duplicates (createBranch's 422-already-exists
// handling makes that safe to re-run).

export async function pushDraftBranch(site, draft, files) {
  const branchName = `action-center/${draft.action_type}-${draft.id}`;
  try {
    const baseSha = await getBranchSha(site, STAGE_BRANCH);
    await createBranch(site, branchName, baseSha);

    for (const f of files) {
      const sha = await getFileSha(site, f.path, branchName);
      await putFile(site, {
        path: f.path,
        content: f.content,
        message: `Action Center: apply ${draft.action_type} draft #${draft.id}`,
        branch: branchName,
        sha,
      });
    }

    return { ok: true, branchName };
  } catch (err) {
    return { ok: false, reason: 'github-error', error: err.message };
  }
}

export async function mergeBranchToStage(site, draft, branchName) {
  try {
    const result = await mergeBranch(site, {
      base: STAGE_BRANCH,
      head: branchName,
      commitMessage: `Action Center: merge ${draft.action_type} draft #${draft.id} into stage`,
    });
    return { ok: true, mergeSha: result.sha, mergeUrl: result.htmlUrl, alreadyMerged: result.alreadyMerged };
  } catch (err) {
    return { ok: false, reason: 'github-error', error: err.message };
  }
}

// Opens a real PR from the already-pushed draft branch into `main` — never
// merges it; a human reviews and merges on GitHub (see STAGE_BRANCH comment
// above for why the diff can include unrelated stage/main divergence). The
// PR body calls that out explicitly so a reviewer isn't caught off guard by
// a bigger-than-expected diff.
export async function openPrForBranch(site, draft, branchName) {
  try {
    const { number, url } = await openPullRequest(site, {
      branch: branchName,
      title: `Action Center: ${draft.action_type} draft #${draft.id}`,
      body: `Automated content draft #${draft.id} (${draft.action_type}) generated by the Action Center.\n\n`
          + `Review the diff and merge into \`main\` to publish.\n\n`
          + `**Note:** this branch was forked from \`stage\`, not \`main\` — if \`stage\` has diverged from `
          + `\`main\`, the diff below may include unrelated changes on top of this draft's actual edit. Review accordingly.`,
    });
    return { ok: true, prNumber: number, prUrl: url };
  } catch (err) {
    return { ok: false, reason: 'github-error', error: err.message };
  }
}
