import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { parsePaginationFrontMatter, matchPaginationRoute, paginationBlockedReason, discoverPaginationRoutes } from './pagination-routes.js';

// The real front matter from zunkireelabs-web, which is what prompted this.
const GLOSSARY = `---
pagination:
  data: glossary
  size: 1
  alias: term
  addAllPagesToCollections: true
layout: glossary-term.njk
permalink: /glossary/{{ term.id }}/
eleventyComputed:
  title: "{{ term.term | safe }} | AI Glossary"
---
body`;

describe('parsePaginationFrontMatter', () => {
  test('reads the route, data source, id field and layout from real front matter', () => {
    const fm = parsePaginationFrontMatter(GLOSSARY);
    assert.equal(fm.data, 'glossary');
    assert.equal(fm.alias, 'term');
    assert.equal(fm.layout, 'glossary-term.njk');
    assert.equal(fm.routePrefix, '/glossary');
    assert.equal(fm.idField, 'id', 'derived from the permalink expression, not assumed');
  });

  test('ignores templates that do not paginate — this module only claims generated pages', () => {
    assert.equal(parsePaginationFrontMatter('---\nlayout: base.njk\ntitle: About\n---\nbody'), null);
    assert.equal(parsePaginationFrontMatter('no front matter at all'), null);
  });
});

describe('matchPaginationRoute', () => {
  const routes = [{ routePrefix: '/glossary', template: 't.njk', idField: 'id' }, { routePrefix: '/compare', template: 'c.njk', idField: 'id' }];

  test('matches a generated URL to the route that produces it', () => {
    assert.equal(matchPaginationRoute('https://x.com/glossary/rag/', routes).template, 't.njk');
    assert.equal(matchPaginationRoute('https://x.com/compare/a-vs-b/', routes).template, 'c.njk');
  });

  test('does not claim unrelated pages', () => {
    assert.equal(matchPaginationRoute('https://x.com/about/', routes), null);
    // Prefix must be a whole segment — /glossaryfoo is not a glossary page.
    assert.equal(matchPaginationRoute('https://x.com/glossaryfoo/', routes), null);
  });
});

describe('paginationBlockedReason', () => {
  const route = { routePrefix: '/glossary', template: 'src/glossary/glossary-terms.njk', dataFile: 'src/_data/glossary.js', idField: 'id', layout: 'glossary-term.njk', alias: 'term' };

  test('names the real mechanism instead of asking for a file mapping', () => {
    const r = paginationBlockedReason(route, 'expand-content');
    assert.match(r, /generated by src\/glossary\/glossary-terms\.njk/);
    assert.match(r, /src\/_data\/glossary\.js/);
    assert.match(r, /matched by "id"/);
    assert.match(r, /rewrite every page in the family/, 'must say why mapping it would be wrong, not just that it is missing');
    assert.doesNotMatch(r, /connect-repo/, 'the old advice would not have fixed this');
  });

  test('degrades honestly when the data file could not be located', () => {
    const r = paginationBlockedReason({ ...route, dataFile: null }, 'schema');
    assert.match(r, /its source data/);
    assert.doesNotMatch(r, /null/);
  });
});

describe('discoverPaginationRoutes', () => {
  const site = { id: 1, repo_owner: 'a', repo_name: 'b', repo_default_branch: 'main' };
  const files = ['src/glossary/glossary-terms.njk', 'src/_data/glossary.js', 'src/pages/about.njk', 'src/_includes/layouts/glossary-term.njk'];

  test('finds the generator and pairs it with its real data file', async () => {
    const routes = await discoverPaginationRoutes(site, {
      fetchTree: async () => ({ files, truncated: false }),
      fetchFile: async (s, f) => ({ content: f.endsWith('glossary-terms.njk') ? GLOSSARY : '---\nlayout: base.njk\n---' }),
    });

    assert.equal(routes.length, 1);
    assert.equal(routes[0].dataFile, 'src/_data/glossary.js');
    assert.equal(routes[0].routePrefix, '/glossary');
  });

  test('never treats a layout or a data file as a page generator', async () => {
    const routes = await discoverPaginationRoutes(site, {
      fetchTree: async () => ({ files: ['src/_includes/layouts/glossary-term.njk', 'src/_data/glossary.js'], truncated: false }),
      fetchFile: async () => ({ content: GLOSSARY }),
    });
    assert.deepEqual(routes, []);
  });

  test('excludes a root-level permalink, which would otherwise claim every URL', async () => {
    const rootGen = GLOSSARY.replace('permalink: /glossary/{{ term.id }}/', 'permalink: /{{ term.id }}/');
    const routes = await discoverPaginationRoutes(site, {
      fetchTree: async () => ({ files: ['src/root.njk'], truncated: false }),
      fetchFile: async () => ({ content: rootGen }),
    });
    assert.deepEqual(routes, []);
  });
});
