import { test, describe, mock, beforeEach } from 'node:test';
import assert from 'node:assert/strict';

const resolve = (p) => new URL(p, import.meta.url).href;

let savedConfig = null;
mock.module(resolve('../../db.js'), {
  namedExports: {
    updateSiteRepoConfig: async ({ siteId, urlFileMap }) => {
      savedConfig = { siteId, urlFileMap };
      return { id: siteId, url_file_map: urlFileMap, repo_owner: 'a', repo_name: 'b' };
    },
  },
});

let recordedRepairs = [];
mock.module(resolve('../../store/capability-repairs.js'), {
  namedExports: {
    recordCapabilityRepair: async (siteId, attempt) => { recordedRepairs.push({ siteId, ...attempt }); },
  },
});

const { discoverDataArrayAdapterConfig, healPaginationAdapter } = await import('./pagination-adapter-discovery.js');

beforeEach(() => { savedConfig = null; recordedRepairs = []; });

// Realistic shape of the case that prompted this: /locations/bhaktapur/,
// generated by src/locations/location-pages.njk from src/_data/locations.js,
// where the template renders `location.description` and `location.faqItems`.
const ROUTE = {
  template: 'src/locations/location-pages.njk',
  routePrefix: '/locations',
  idField: 'id',
  alias: 'location',
  dataFile: 'src/_data/locations.js',
  dataFileAmbiguous: false,
  layout: 'location.njk',
};

const TEMPLATE_SOURCE = `
<h1>{{ location.name }}</h1>
<p>{{ location.description | safe }}</p>
{% for item in location.faqItems %}
  <div>{{ item.question }}</div>
{% endfor %}
`;

function locationsJs() {
  return `export default [
  {
    id: 'kathmandu',
    name: 'Kathmandu',
    description: 'Kathmandu is the capital.',
    faqItems: [],
  },
  {
    id: 'bhaktapur',
    name: 'Bhaktapur',
    description: 'Bhaktapur is a historic city.',
    faqItems: [],
  },
];
`;
}

const site = { id: 1, repo_owner: 'a', repo_name: 'b', repo_default_branch: 'main', url_file_map: {} };

function fetchFileFor({ data, template }) {
  return async (s, path) => {
    if (path === ROUTE.dataFile) return { content: data };
    if (path === ROUTE.template) return { content: template };
    return null;
  };
}

describe('discoverDataArrayAdapterConfig', () => {
  test('resolves the real field from data + real template rendering, for a scalar action type', async () => {
    const result = await discoverDataArrayAdapterConfig(
      site, ROUTE, 'expand-content', 'https://x.com/locations/bhaktapur/',
      { fetchFile: fetchFileFor({ data: locationsJs(), template: TEMPLATE_SOURCE }) },
    );
    assert.ok(result, 'should resolve — description is the one field both present on the entry and rendered by the template');
    assert.deepEqual(result.config, {
      id: 'data-array-content', format: 'js-export-array', dataFile: ROUTE.dataFile, idField: 'id',
      fields: { expandedContent: 'description' },
    });
  });

  test('resolves an items-array field for faq/qa-content', async () => {
    const result = await discoverDataArrayAdapterConfig(
      site, ROUTE, 'faq', 'https://x.com/locations/bhaktapur/',
      { fetchFile: fetchFileFor({ data: locationsJs(), template: TEMPLATE_SOURCE }) },
    );
    assert.ok(result);
    assert.equal(result.config.itemsField, 'faqItems');
    assert.equal(result.config.id, 'data-array-content');
  });

  test('refuses when the template renders more than one field of the right shape (real ambiguity, not a guess)', async () => {
    const ambiguousTemplate = '{{ location.description | safe }} {{ location.summary | safe }}';
    const data = `export default [
      { id: 'bhaktapur', description: 'a', summary: 'b', faqItems: [] },
    ];\n`;
    const result = await discoverDataArrayAdapterConfig(
      site, ROUTE, 'expand-content', 'https://x.com/locations/bhaktapur/',
      { fetchFile: fetchFileFor({ data, template: ambiguousTemplate }) },
    );
    assert.equal(result, null);
  });

  test('refuses a plain escaped field even if it is the only field referenced — rendering it raw would show literal markup, not HTML', async () => {
    const escapedOnlyTemplate = '{{ location.description }}'; // no | safe — plain, escaped interpolation
    const data = "export default [{ id: 'bhaktapur', description: 'a', faqItems: [] }];\n";
    const result = await discoverDataArrayAdapterConfig(
      site, ROUTE, 'expand-content', 'https://x.com/locations/bhaktapur/',
      { fetchFile: fetchFileFor({ data, template: escapedOnlyTemplate }) },
    );
    assert.equal(result, null);
  });

  test('refuses when the data file has no unambiguous matching entry', async () => {
    const data = `export default [{ id: 'kathmandu', description: 'x', faqItems: [] }];\n`;
    const result = await discoverDataArrayAdapterConfig(
      site, ROUTE, 'expand-content', 'https://x.com/locations/bhaktapur/',
      { fetchFile: fetchFileFor({ data, template: TEMPLATE_SOURCE }) },
    );
    assert.equal(result, null);
  });

  test('refuses for an action type with no single-field shape (meta-title)', async () => {
    const result = await discoverDataArrayAdapterConfig(
      site, ROUTE, 'meta-title', 'https://x.com/locations/bhaktapur/',
      { fetchFile: fetchFileFor({ data: locationsJs(), template: TEMPLATE_SOURCE }) },
    );
    assert.equal(result, null);
  });

  test('refuses a route with an ambiguous data file rather than attempting discovery', async () => {
    const result = await discoverDataArrayAdapterConfig(
      site, { ...ROUTE, dataFileAmbiguous: true }, 'expand-content', 'https://x.com/locations/bhaktapur/',
      { fetchFile: fetchFileFor({ data: locationsJs(), template: TEMPLATE_SOURCE }) },
    );
    assert.equal(result, null);
  });
});

describe('healPaginationAdapter', () => {
  test('persists a patterns[] entry covering the whole route family, not just the triggering page', async () => {
    const healed = await healPaginationAdapter(site, ROUTE, 'expand-content', 'https://x.com/locations/bhaktapur/', {
      fetchFile: fetchFileFor({ data: locationsJs(), template: TEMPLATE_SOURCE }),
      log: { warn() {}, log() {} },
    });

    assert.ok(healed, 'should return the updated site');
    assert.equal(savedConfig.siteId, site.id);
    const pattern = savedConfig.urlFileMap.patterns.find((p) => p.match === '^/locations/[^/]+/?$');
    assert.ok(pattern, 'covers every /locations/:slug page, not just bhaktapur');
    assert.deepEqual(pattern.adapters['expand-content'], {
      id: 'data-array-content', format: 'js-export-array', dataFile: ROUTE.dataFile, idField: 'id',
      fields: { expandedContent: 'description' },
    });

    const repaired = recordedRepairs.find((r) => r.outcome === 'repaired');
    assert.ok(repaired, 'logs the auto-configuration for audit visibility');
    assert.equal(repaired.capabilityType, 'url-file-map-adapter');
  });

  test('is idempotent — a second call for an already-configured route family is a no-op', async () => {
    const deps = { fetchFile: fetchFileFor({ data: locationsJs(), template: TEMPLATE_SOURCE }), log: { warn() {}, log() {} } };
    const once = await healPaginationAdapter(site, ROUTE, 'expand-content', 'https://x.com/locations/bhaktapur/', deps);
    const siteWithAdapter = { ...site, url_file_map: once.url_file_map };
    savedConfig = null;
    const twice = await healPaginationAdapter(siteWithAdapter, ROUTE, 'expand-content', 'https://x.com/locations/kathmandu/', deps);
    assert.equal(twice, null, 'already configured — nothing to write');
    assert.equal(savedConfig, null);
  });

  test('logs an "ambiguous" outcome and writes nothing when the field cannot be resolved', async () => {
    const ambiguousTemplate = '{{ location.description }} {{ location.summary }}';
    const data = `export default [
      { id: 'bhaktapur', description: 'a', summary: 'b', faqItems: [] },
    ];\n`;
    const healed = await healPaginationAdapter(site, ROUTE, 'expand-content', 'https://x.com/locations/bhaktapur/', {
      fetchFile: fetchFileFor({ data, template: ambiguousTemplate }), log: { warn() {}, log() {} },
    });
    assert.equal(healed, null);
    assert.equal(savedConfig, null);
    const ambiguous = recordedRepairs.find((r) => r.outcome === 'ambiguous');
    assert.ok(ambiguous);
  });
});
