import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { marked } from 'marked';
import { chromium } from 'playwright';

// PREMIUM CLIENT-FACING BASELINE REPORT PDF.
//
// Replaces the earlier version of this file, which just ran the LLM's
// narrative_md through `marked` and printed it — heading, paragraph,
// heading, bullet list, repeat, at Letter size with no branding. This
// builds a real multi-page A4 document driven directly from the STRUCTURED
// snapshot (kpi_snapshot, issues_snapshot — see agents/lib/baseline-report.js)
// rather than re-parsing the LLM's freeform markdown for the numeric/
// tabular sections, so every number, table and row is exactly what is
// stored, laid out deliberately instead of left to whatever `marked` and
// the browser's default pagination produce.
//
// The one place real LLM prose is used is the Executive Assessment
// paragraph on the Website Snapshot page — extracted verbatim from
// narrative_md's "Where Your Website Stood" section (extractMarkdownSection
// below) — per the explicit instruction to use the existing writing, not
// invented copy, for that one editorial block. Every other caption/sentence
// in this document is a DETERMINISTIC template built from real numbers
// already in the snapshot (see scoreExplanation/auditScopeText/etc.) —
// deliberately not narrative-text-dependent, since narrative_md is
// regenerated by an LLM on every run and its exact wording is not a stable
// thing to build a rendering pipeline around.
//
// Branding: NOT the marketing site's (zunkireelabs-web) stylized wordmark
// SVG — this platform's own actual brand presentation, the one a user
// already sees on every screen of the dashboard, is icon + plain text
// (web/src/components/Sidebar.jsx:200-208: `sites[0].logo_data_url` image
// next to a `{sites[0].name}` text span, no baked-in logotype). The icon
// PNG here is that exact same asset — sites.logo_data_url for site id 1
// ("Zunkiree Labs" itself), decoded and saved byte-for-byte as
// report/assets/zunkireelabs-icon.png, not redrawn. Brand palette from
// zunkireelabs-web's tailwind.config.js: zunkiree red #eb1600 as the only
// accent, navy/near-black #0f172a for primary text, slate #64748b for muted
// text. Typography is that repo's own Google Fonts pairing, DM Sans
// (display/body) + DM Mono (statistics), loaded the way the live site does.

const __dirname = dirname(fileURLToPath(import.meta.url));
const LOGO_ICON_BASE64 = readFileSync(join(__dirname, 'assets/zunkireelabs-icon.png')).toString('base64');
const LOGO_ICON_SRC = `data:image/png;base64,${LOGO_ICON_BASE64}`;

// Mirrors the dashboard's own icon+name pairing (see comment above) at
// whatever size a given placement needs — the cover's is large, the
// repeating page header/footer's is small.
function brandMark(iconPx, textPx) {
  return `<span class="brand-mark"><img src="${LOGO_ICON_SRC}" alt="Zunkiree Labs" style="height:${iconPx}px;width:${iconPx}px;border-radius:${Math.round(iconPx * 0.22)}px;display:block;" /><span class="brand-mark-text" style="font-size:${textPx}px;">Zunkiree Labs</span></span>`;
}

const BRAND = {
  red: '#eb1600',
  navy: '#0f172a',
  muted: '#64748b',
  faint: '#94a3b8',
  divider: '#e2e8f0',
  surface: '#f9f7f4',
};

function escapeHtml(s) {
  return String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

const numberFormat = (n) => Number(n ?? 0).toLocaleString('en-US');

// Pulls one `## Heading` section's real text out of the LLM's narrative_md,
// so the Executive Assessment block on page 2 quotes the model's actual
// written words rather than a value re-derived here. Returns '' (never a
// fabricated fallback sentence) when the heading is missing — the caller is
// responsible for handling an empty result honestly.
export function extractMarkdownSection(md, heading) {
  if (!md) return '';
  const re = new RegExp(`^##\\s+${heading.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*$`, 'm');
  const m = re.exec(md);
  if (!m) return '';
  const rest = md.slice(m.index + m[0].length);
  const next = rest.search(/^##\s+/m);
  return (next === -1 ? rest : rest.slice(0, next)).trim();
}

// A short, human title for a recommendation ROW — derived from the real
// `type`/`issue` fields already on the record (never a new fact), the same
// way a person skimming the sentence would summarize it. Falls back to the
// recommendation's own type name, Title Cased, for anything unrecognized —
// never invents a description the data doesn't support.
export function recommendationTitle(item) {
  const issue = String(item.issue || '');
  if (item.type === 'faq') return 'Add FAQ';
  if (item.type === 'landing-page') return 'Generate Landing Page';
  if (item.type === 'schema' || item.type === 'schema-repair') return 'Add Schema Markup';
  if (item.type === 'broken-link-fix') return 'Remove Invalid Citation';
  if (item.type === 'alt-text') return 'Add Image Alt Text';
  if (/comparison|alternatives|best of/i.test(issue)) return 'Add Comparison Content';
  if (/author|byline/i.test(issue)) return 'Add Author/Byline Markup';
  if (/breadcrumb/i.test(issue)) return 'Add Breadcrumbs';
  if (/freshness|last.?updated/i.test(issue)) return 'Add Freshness Signal';
  return String(item.type || 'Recommendation').replace(/[-_]+/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

// Client-facing "what we'll do" + "why it helps you get found" for a
// recommendation row — the plain-language counterpart to recommendationTitle
// above (which stays an internal/technical label, still used verbatim by the
// existing test suite). Keyed off the same real type/issue fields, never a
// new fact; falls back to a generic-but-honest pair for anything unrecognized
// rather than printing a raw internal type name in a client's PDF.
export function recommendationClientCopy(item) {
  const issue = String(item.issue || '');
  if (item.type === 'faq') return { action: 'Answer the real questions your customers ask', benefit: 'so AI tools and Google can quote your answer directly instead of a competitor\'s' };
  if (item.type === 'landing-page') return { action: 'Build a dedicated page for a topic you\'re missing', benefit: 'so you show up for searches you currently don\'t rank for at all' };
  if (item.type === 'schema' || item.type === 'schema-repair') return { action: 'Add the technical tags search engines read', benefit: 'so Google and AI assistants understand exactly what your page is about' };
  if (item.type === 'broken-link-fix') return { action: 'Fix a link pointing somewhere it shouldn\'t', benefit: 'so visitors and AI tools don\'t hit a dead end on your site' };
  if (item.type === 'alt-text') return { action: 'Describe your images for search engines', benefit: 'so your images can be found in search and understood by AI' };
  if (/comparison|alternatives|best of/i.test(issue)) return { action: 'Show how you compare to the alternatives', benefit: 'so people actively deciding between options can find and pick you' };
  if (/author|byline/i.test(issue)) return { action: 'Show who wrote your content', benefit: 'so AI assistants trust and credit your expertise when citing you' };
  if (/breadcrumb/i.test(issue)) return { action: 'Add clear page navigation trails', benefit: 'so search engines understand how your site fits together' };
  if (/freshness|last.?updated/i.test(issue)) return { action: 'Show when your content was last updated', benefit: 'so search engines know your information is current' };
  return { action: recommendationTitle(item), benefit: 'so your site is easier to find and trust' };
}

const PRIORITY_ORDER = { high: 0, medium: 1, low: 2 };
// Plain ordering language for a client, not internal priority jargon —
// "HIGH PRIORITY" describes our triage process, not something a client
// needs to parse; "we're doing this first" describes the same fact in terms
// of what happens to them.
const PRIORITY_ORDER_LABEL = { high: 'DOING THIS FIRST', medium: 'NEXT UP', low: 'ALSO ON THE LIST' };
const PRIORITY_COLOR = { high: BRAND.red, medium: BRAND.navy, low: BRAND.muted };

// Trimmed from 8 to 5 for the 4-page compact layout — the "How Coming To
// Us Helps" page now shares its page with the autonomous-agent note and the
// roadmap, so it no longer has a full page to itself for the issue list.
const MAX_RECOMMENDATION_ROWS = 5;

// True when the row's supporting sentence would just restate its own title
// verbatim — real data on Admizz's actual report: the record's `issue` field
// for a faq/landing-page/broken-link-fix recommendation IS already the short
// form ("Add FAQ" / "Add FAQ"), so printing both looked like a bug, not a
// title + description. Ignores trailing punctuation/case only — never
// rewrites either string.
export function descriptionRepeatsTitle(title, issue) {
  const norm = (s) => String(s || '').trim().toLowerCase().replace(/[.\s]+$/, '');
  return norm(title) === norm(issue);
}

// Featured list = the highest-priority REPRESENTATIVE of each distinct issue
// type, not the raw top N by priority. Real data on Admizz's audit: of 217
// open items, the first 8 by priority alone were "Add Author/Byline Markup"
// three times and "Add Comparison Content" twice — genuinely the highest-
// priority items, but a report meant to show the SHAPE of what's missing is
// stronger showing 6-8 distinct problems once each than the same headline
// repeated. Every row shown is still a real record for a real page; this
// only decides which of several equivalent real records represents its type.
export function selectFeaturedRecommendations(items, max) {
  const sorted = [...items].sort((a, b) => (PRIORITY_ORDER[a.priority] ?? 9) - (PRIORITY_ORDER[b.priority] ?? 9));
  const seen = new Set();
  const out = [];
  for (const item of sorted) {
    const key = recommendationTitle(item).toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(item);
    if (out.length >= max) break;
  }
  return out;
}

export function scoreStatusWord(score) {
  if (score < 40) return 'NEEDS ATTENTION';
  if (score < 70) return 'DEVELOPING';
  return 'STRONG';
}

// A real, deterministic "how do they rank against you" line — the client
// asked specifically for a rank comparison here, not the LLM's free-text
// verdict (which on a real report drifted toward describing one on-page
// signal like FAQ schema instead of an actual scoreline). Uses the same
// same-methodology structural score both sites were crawled with (see
// competitor-analysis.js summarizeAnalysis / store/competitor-profiles.js
// getLatestCompetitorScores) — falls back to the LLM's prose only when no
// real score pair exists yet for this domain.
// A short "the [industry] space" phrase for the competitor headline below —
// falls back to a still-concrete "your market" when site_profiles.industry
// hasn't been set for this client yet, never a blank.
function industryLabel(industry) {
  return industry ? `the ${industry} space` : 'your market';
}

// The primary, client-facing line for a competitor row — leads with an
// encouraging, forward-looking sentence tied to the client's own industry
// and what WE do about the gap, rather than a bare score comparison (which
// reads as a cold report card, not something that makes a client excited to
// work with us). The real score comparison (competitorScoreBadge below)
// still exists, but only as small supporting
// evidence underneath this sentence, never as the headline.
export function competitorPositiveLine(c, industry) {
  const label = industryLabel(industry);
  if (c.ownScore == null || c.competitorScore == null) {
    return `${c.domain} is a real competitor for ${label} search terms — here's how we help you compete.`;
  }
  if (c.competitorScore > c.ownScore) {
    return `${c.domain} is currently ahead of you in ${label} — closing gaps like this is exactly what our daily system does.`;
  }
  return `Good news — you're already ranking ahead of ${c.domain} in ${label}. We'll help you extend that lead.`;
}

// Small supporting evidence line under the headline above — the real number,
// kept, just no longer the first thing a client reads.
export function competitorScoreBadge(c) {
  if (c.ownScore == null || c.competitorScore == null) return '';
  return `<span class="competitor-rank">${c.competitorScore}/100 vs. your ${c.ownScore}/100</span>`;
}

// The label in front of whatTheyDoBetter (the LLM's one-sentence verdict) —
// must agree with competitorPositiveLine's headline above it. "Where
// they're ahead" only makes sense when the competitor's real score is
// actually higher; printing it under a "you're already ahead" headline
// would contradict the sentence directly above it.
function competitorDetailLabel(c) {
  if (c.ownScore == null || c.competitorScore == null) return 'What we found:';
  return c.competitorScore > c.ownScore ? "Where they're ahead:" : 'One thing to watch:';
}

// Deterministic, real-data-grounded caption — see this file's top comment
// for why this is computed rather than pulled from narrative_md.
function scoreExplanation(score) {
  if (score < 40) {
    return 'This score reflects real gaps across technical SEO, content depth and AI-readiness — most of which are addressed by the recommendations on the following pages.';
  }
  if (score < 70) {
    return 'This score reflects a partially optimized site with specific, addressable gaps — the recommendations on the following pages close them.';
  }
  return 'This score reflects a well-optimized site. The recommendations on the following pages are refinements rather than fundamentals.';
}

// A concrete, industry-flavored "someone searching for you" moment for the
// Why This Matters page — matched by substring against site_profiles.industry
// (free text from the data-analyst agent, e.g. "K-12 Education", "Healthcare
// / Urgent Care") so close variants still land on the right example. Falls
// back to a generic-but-still-concrete phrasing when the industry is unknown
// or doesn't match any entry, never a blank/technical placeholder.
const INDUSTRY_SEARCH_EXAMPLES = [
  ['educat', 'a parent searching "best [program] near me" or asking an AI assistant to compare schools'],
  ['health', 'a patient searching "[condition or service] near me" or asking "does anyone nearby treat this"'],
  ['medical', 'a patient searching "[condition or service] near me" or asking "does anyone nearby treat this"'],
  ['dental', 'someone searching "dentist near me" or asking an AI assistant which one takes their insurance'],
  ['real estate', 'a buyer searching "homes for sale in [area]" or asking an AI assistant to compare listings'],
  ['legal', 'someone searching "[practice area] lawyer near me" after a stressful event'],
  ['law', 'someone searching "[practice area] lawyer near me" after a stressful event'],
  ['ecommerce', 'a shopper searching "best [product] under $[price]" or asking an AI assistant what to buy'],
  ['retail', 'a shopper searching "best [product] under $[price]" or asking an AI assistant what to buy'],
  ['hospitality', 'a traveler searching "[type] hotel in [city]" or asking an AI assistant to plan a trip'],
  ['travel', 'a traveler searching "best time to visit [destination]" or asking an AI assistant to plan a trip'],
  ['finance', 'someone searching "[service] near me" or asking an AI assistant to compare options'],
  ['insurance', 'someone searching "[coverage type] near me" or asking an AI assistant to compare quotes'],
  ['fitness', 'someone searching "[type] gym near me" or asking an AI assistant for a recommendation'],
  ['restaurant', 'someone searching "best [cuisine] near me" or asking an AI assistant where to eat'],
  ['home service', 'someone searching "[service] near me" right after something breaks'],
  ['construction', 'someone searching "[service] near me" right after something breaks'],
];

function industrySearchExample(industry, siteName) {
  const key = String(industry || '').toLowerCase();
  const match = INDUSTRY_SEARCH_EXAMPLES.find(([needle]) => key.includes(needle));
  return match ? match[1] : `someone searching for exactly what ${siteName} offers`;
}

function pageChrome({ eyebrow, sectionNumber, sectionTitle, body, footerNote, siteName, dateLabel, pageNumber }) {
  return `
  <section class="page">
    <header class="page-header">
      <div class="page-header-logo">${brandMark(16, 11)}</div>
      <div class="page-header-meta">
        <span class="page-header-label">Baseline Report</span>
        <span class="page-header-sub">${escapeHtml(siteName)} · ${escapeHtml(dateLabel)}</span>
      </div>
    </header>
    <div class="page-divider"></div>
    ${sectionNumber ? `
    <div class="section-marker">
      <span class="section-number">${sectionNumber}</span>
      <span class="section-title">${escapeHtml(sectionTitle)}</span>
    </div>` : ''}
    ${eyebrow ? `<p class="eyebrow">${escapeHtml(eyebrow)}</p>` : ''}
    <div class="page-body">${body}</div>
    <footer class="page-footer">
      <div class="page-footer-divider"></div>
      <div class="page-footer-row">
        <span class="page-footer-brand">Zunkiree Labs <span class="page-footer-dim">— AI-Powered Website Growth</span></span>
        <span class="page-footer-page">${pageNumber}</span>
      </div>
      ${footerNote ? `<p class="page-footer-note">${footerNote}</p>` : ''}
    </footer>
  </section>`;
}

// Page 1 — "Why This Matters": what SEO/AEO/GEO actually are, in plain
// language, what each needs to work, and a concrete picture of where this
// specific client could be showing up once all three are in place. Includes
// a compact cover treatment (title/client/date) instead of a full separate
// cover page, per the compaction pass — the brand header/footer chrome
// already carries the branding on every page.
function whyMattersPage({ siteName, industry, dateLabel }) {
  const example = industrySearchExample(industry, siteName);
  const body = `
    <div class="hero">
      <h1 class="hero-title">Digital Visibility<br/>Baseline Report</h1>
      <p class="hero-client">${escapeHtml(siteName)}</p>
      <p class="hero-date">${escapeHtml(dateLabel).toUpperCase()}</p>
    </div>
    <p class="section-intro">Three things decide whether people — and the AI tools they now search with — find ${escapeHtml(siteName)}.</p>
    <div class="explainer-list">
      <div class="explainer">
        <p class="explainer-term">SEO <span class="explainer-full">— Search Engine Optimization</span></p>
        <p class="explainer-copy">Making sure Google can find your site, understand what it offers, and rank it high enough that people actually click. Needs a technically healthy website, content that answers real questions, and other trustworthy sites linking to you.</p>
      </div>
      <div class="explainer">
        <p class="explainer-term">AEO <span class="explainer-full">— Answer Engine Optimization</span></p>
        <p class="explainer-copy">Making sure voice assistants and AI-powered search results (like Google's AI Overviews) can pull a short, accurate answer straight from your site instead of a competitor's. Needs clear FAQs, direct answers near the top of a page, and markup that tells AI what your content means.</p>
      </div>
      <div class="explainer">
        <p class="explainer-term">GEO <span class="explainer-full">— Generative Engine Optimization</span></p>
        <p class="explainer-copy">Making sure AI chatbots like ChatGPT, Claude, and Gemini know your business exists and recommend it when someone asks a relevant question. Needs a site that's easy for AI to read, consistent facts about your business across the web, and content AI can confidently cite.</p>
      </div>
    </div>
    <div class="callout">
      <p class="callout-copy">Picture ${example}. With SEO, AEO, and GEO all working together, that search ends with ${escapeHtml(siteName)} — found on Google, quoted in an AI Overview, and recommended by name when someone asks ChatGPT.</p>
    </div>`;
  return pageChrome({
    sectionNumber: '01', sectionTitle: 'Why This Matters',
    body, siteName, dateLabel, pageNumber: 1,
  });
}

// Page 2 — "Where You Stand Today": plain-language baseline of current
// search/AI visibility and website health, plus real named competitors.
function standTodayPage({ kpi, auditFindings, aiVisibility, competitors, execAssessmentHtml, siteName, dateLabel, industry }) {
  const score = kpi.healthScore ?? 0;
  const status = scoreStatusWord(score);
  const findingsCount = auditFindings ? numberFormat(auditFindings.total) : null;
  const findingsQualifier = auditFindings?.truncated ? 'at least ' : '';

  const aiBlock = aiVisibility?.available
    ? `<div class="mini-score"><span class="mini-score-value">${aiVisibility.overall}<span class="mini-score-max">/100</span></span><span class="mini-score-label">AI Visibility — can AI tools read and cite your site</span></div>`
    : `<div class="mini-score"><span class="mini-score-value">—</span><span class="mini-score-label">AI Visibility — measurement not run yet, will appear in a future report</span></div>`;

  const competitorRows = (competitors && competitors.length)
    ? competitors.map((c) => `
    <div class="competitor-row">
      <div class="competitor-head">
        <span class="competitor-domain">${escapeHtml(c.domain)}</span>
        ${competitorScoreBadge(c)}
      </div>
      <p class="competitor-headline">${escapeHtml(competitorPositiveLine(c, industry))}</p>
      ${c.whatTheyDoBetter ? `<p class="competitor-copy">${escapeHtml(competitorDetailLabel(c))} ${escapeHtml(c.whatTheyDoBetter)}</p>` : ''}
    </div>`).join('')
    : `<p class="section-intro">We're still identifying your closest competitors — this will be filled in as soon as that analysis completes.</p>`;

  const body = `
    <div class="score-moment">
      <span class="score-value">${score} <span class="score-max">/ 100</span></span>
      <span class="score-status" style="color:${status === 'NEEDS ATTENTION' ? BRAND.red : BRAND.navy}">${status}</span>
      <div class="score-bar"><div class="score-bar-fill" style="width:${Math.max(2, Math.min(100, score))}%"></div></div>
      <p class="score-caption">${scoreExplanation(score)}${auditFindings ? ` We reviewed ${numberFormat(auditFindings.pagesAffected)} pages and found ${findingsQualifier}${findingsCount} things to fix.` : ''}</p>
    </div>
    ${aiBlock}
    ${execAssessmentHtml ? `<div class="assessment"><p class="label-small">Where You Stand</p><div class="assessment-copy">${execAssessmentHtml}</div></div>` : ''}
    <div class="competitors">
      <p class="label-small">Who You're Up Against</p>
      ${competitorRows}
    </div>`;
  return pageChrome({
    sectionNumber: '02', sectionTitle: 'Where You Stand Today',
    body, siteName, dateLabel, pageNumber: 2,
  });
}

// Autonomous agent behavior, described once here rather than baked into the
// deterministic per-item recommendation copy — a static, accurate
// description of the always-on system, not a claim about any specific item.
const AUTONOMOUS_AGENT_COPY = 'Every day, our system automatically reviews your website — checking technical health, content gaps, and how well AI tools understand your site. Low-risk issues, like missing alt text or a broken internal link, get fixed automatically. Anything bigger — a structural change, new content, a decision that affects your brand — is flagged for our team to review with you first.';

const ROADMAP_STAGES = [
  { n: '01', title: 'Foundation', copy: 'Fix the technical and structural issues so search engines and AI can properly read your site.' },
  { n: '02', title: 'Content', copy: 'Close content gaps and answer the real questions your customers are asking.' },
  { n: '03', title: 'Authority', copy: 'Build the citations, links, and trust signals that make your site worth recommending.' },
  { n: '04', title: 'Measurement', copy: 'Track real movement against this baseline and report on what\'s working.' },
];

// Page 3 — "How Coming To Us Helps": what you have vs. what you lack (from
// the real audit), the autonomous agent, and the phased roadmap.
function howWeHelpPage({ openRecommendations, siteName, dateLabel }) {
  const items = selectFeaturedRecommendations(openRecommendations?.items || [], MAX_RECOMMENDATION_ROWS);
  const rows = items.map((item, i) => {
    const num = String(i + 1).padStart(2, '0');
    const { action, benefit } = recommendationClientCopy(item);
    return `
    <div class="rec-row">
      <span class="rec-num">${num}</span>
      <div class="rec-body">
        <p class="rec-title">${escapeHtml(action)}</p>
        <p class="rec-desc">${escapeHtml(benefit)}</p>
      </div>
      <span class="rec-priority" style="color:${PRIORITY_COLOR[item.priority] || BRAND.muted}">${PRIORITY_ORDER_LABEL[item.priority] || ''}</span>
    </div>`;
  }).join('<div class="rec-divider"></div>');
  const total = openRecommendations?.total || items.length;

  const stages = ROADMAP_STAGES.map((s, i) => `
    <div class="roadmap-stage">
      <div class="roadmap-marker"><span>${s.n}</span></div>
      <div class="roadmap-text">
        <p class="roadmap-title">${escapeHtml(s.title)}</p>
        <p class="roadmap-copy">${escapeHtml(s.copy)}</p>
      </div>
    </div>${i < ROADMAP_STAGES.length - 1 ? '<div class="roadmap-line"></div>' : ''}`).join('');

  const body = `
    <p class="section-intro">This is how we grow ${escapeHtml(siteName)}'s visibility — turning what's holding you back today into real movement in search and AI rankings. Out of ${numberFormat(total)} things we found, here's where we start:</p>
    <div class="rec-list">${rows}</div>
    <div class="agent-note">
      <p class="label-small">Every Day, Automatically</p>
      <p class="agent-copy">${AUTONOMOUS_AGENT_COPY}</p>
    </div>
    <div class="roadmap">
      <p class="label-small">From Baseline To Growth</p>
      ${stages}
    </div>`;
  return pageChrome({
    sectionNumber: '03', sectionTitle: 'How Coming To Us Helps',
    body, siteName, dateLabel, pageNumber: 3,
  });
}

// Page 4 — "Getting Started": what we need from the client and what happens
// right after kickoff.
function gettingStartedPage({ siteName, dateLabel }) {
  const body = `
    <p class="section-intro">Here's what we'll need from you to get started, and what happens right after.</p>
    <div class="starter-block">
      <p class="label-small">What We'll Need From You</p>
      <ul class="starter-list">
        <li>Access to Google Search Console and Google Analytics for ${escapeHtml(siteName)}</li>
        <li>One point of contact who can approve bigger changes we flag</li>
        <li>Access to your website/CMS, so low-risk fixes can be applied directly</li>
      </ul>
    </div>
    <div class="starter-block">
      <p class="label-small">Right After Kickoff</p>
      <ul class="starter-list">
        <li>We run a full audit and freeze this report as your day-0 baseline</li>
        <li>Our system starts its daily checks immediately</li>
        <li>You'll see your first fixes within days, and a Milestones report tracking real progress against this baseline</li>
      </ul>
    </div>
    <div class="commitment">
      <p class="label-small">Our Commitment</p>
      <p class="commitment-copy">This isn't a one-time report — it's an active system working on ${escapeHtml(siteName)} every single day, moving you from where you stand today toward real, measurable growth. Every fix is logged, every score is tracked, and every future report is measured against this exact baseline — so you always know precisely what's working, in numbers, not promises.</p>
    </div>
    <div class="closing">
      <div class="closing-logo">${brandMark(26, 16)}</div>
      <p class="closing-tag">AI-Powered Website Growth</p>
    </div>`;
  return pageChrome({
    sectionNumber: '04', sectionTitle: 'Getting Started',
    body, siteName, dateLabel, pageNumber: 4,
  });
}

// `report` is a raw baseline_reports row (kpi_snapshot/issues_snapshot/
// narrative_md/generated_at, see store/baseline-reports.js), `site` a raw
// sites row.
export function renderBaselineReportHtml(report, site) {
  const kpi = report.kpi_snapshot || {};
  const issues = report.issues_snapshot || {};
  const dateLabel = new Date(report.generated_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: '2-digit' });
  const execAssessmentHtml = marked.parse(extractMarkdownSection(report.narrative_md, 'Where Your Website Stood') || '');

  const pages = [
    whyMattersPage({ siteName: site.name, industry: kpi.industry, dateLabel }),
    standTodayPage({
      kpi, auditFindings: issues.auditFindings, aiVisibility: issues.aiVisibility,
      competitors: issues.competitors, execAssessmentHtml, siteName: site.name, dateLabel,
      industry: kpi.industry,
    }),
    howWeHelpPage({ openRecommendations: issues.openRecommendations, siteName: site.name, dateLabel }),
    gettingStartedPage({ siteName: site.name, dateLabel }),
  ].join('\n');

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>${escapeHtml(site.name)} — Baseline Report</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,600;9..40,700&display=swap" rel="stylesheet">
<style>${REPORT_CSS}</style>
</head>
<body>
${pages}
</body>
</html>`;
}

const REPORT_CSS = `
  @page { size: A4; margin: 0; }
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; background: ${BRAND.surface}; }
  body { font-family: 'DM Sans', -apple-system, 'Helvetica Neue', Arial, sans-serif; color: ${BRAND.navy}; }
  .page {
    width: 210mm; min-height: 297mm; position: relative;
    background: #fff; padding: 20mm 18mm 16mm; margin: 0 auto;
    display: flex; flex-direction: column;
    page-break-after: always; break-after: page;
    box-shadow: 0 1px 3px rgba(15,23,42,0.08), 0 8px 24px rgba(15,23,42,0.06);
  }
  /* min-height keeps every page a full, presentable A4 sheet (short content
     still reads as a real report page, not a torn-off scrap), but does NOT
     force content to stretch or center to fill it — see .page-body below,
     which is the actual fix for the old "blank gap" bug: content now flows
     from the top and the page simply ends shorter, instead of being padded
     out to fill the full height. */
  .page:last-child { page-break-after: auto; }
  @media print { .page { box-shadow: none; margin: 0; } body { background: #fff; } }

  /* ---- shared header/footer ---- */
  .page-header { display: flex; align-items: center; justify-content: space-between; }
  .brand-mark { display: inline-flex; align-items: center; gap: 2.5mm; }
  .brand-mark-text { font-weight: 700; color: ${BRAND.navy}; letter-spacing: -0.01em; }
  .page-header-meta { text-align: right; }
  .page-header-label { display: block; font-size: 9px; letter-spacing: 0.12em; text-transform: uppercase; color: ${BRAND.faint}; font-weight: 600; }
  .page-header-sub { display: block; font-size: 9px; color: ${BRAND.muted}; margin-top: 2px; }
  .page-divider { height: 1px; background: ${BRAND.divider}; margin: 6mm 0 8mm; }

  .section-marker { display: flex; align-items: baseline; gap: 4mm; margin-bottom: 4mm; }
  .section-number { font-family: 'DM Mono', monospace; font-size: 12px; color: ${BRAND.faint}; }
  .section-title { font-size: 11px; letter-spacing: 0.1em; text-transform: uppercase; font-weight: 700; color: ${BRAND.navy}; }
  .eyebrow { font-size: 10px; letter-spacing: 0.1em; text-transform: uppercase; color: ${BRAND.faint}; }
  .section-intro { font-size: 12.5px; color: ${BRAND.muted}; line-height: 1.6; max-width: 150mm; margin: 0 0 8mm; }

  /* Content flows from the top of the available space and stops — it is
     NOT centered/stretched to fill the full A4 height. That forced
     centering was the source of the earlier "blank gap" bug: a page with
     less content than a full sheet got padded with dead space top and
     bottom instead of just ending sooner. Each of the 4 pages here is now
     also multi-section (e.g. score + AI visibility + competitors on one
     page), so top-anchored flow is also what lets those sections stack
     naturally instead of each being centered independently. */
  .page-body { flex: 1; display: flex; flex-direction: column; }

  .page-footer { margin-top: auto; padding-top: 6mm; }
  .page-footer-divider { height: 1px; background: ${BRAND.divider}; margin-bottom: 3mm; }
  .page-footer-row { display: flex; align-items: center; justify-content: space-between; }
  .page-footer-brand { font-size: 9px; color: ${BRAND.navy}; font-weight: 600; }
  .page-footer-dim { color: ${BRAND.faint}; font-weight: 400; }
  .page-footer-page { font-family: 'DM Mono', monospace; font-size: 9px; color: ${BRAND.faint}; }
  .page-footer-note { font-size: 8.5px; color: ${BRAND.faint}; margin: 2mm 0 0; }

  /* ---- hero (compact cover treatment on page 1, not a full page) ---- */
  .hero { margin-bottom: 10mm; }
  .hero-title { font-size: 32px; line-height: 1.08; font-weight: 700; letter-spacing: -0.01em; margin: 0 0 4mm; color: ${BRAND.navy}; }
  .hero-client { font-size: 15px; font-weight: 500; color: ${BRAND.navy}; margin: 0 0 1mm; }
  .hero-date { font-size: 10px; letter-spacing: 0.1em; color: ${BRAND.faint}; margin: 0; }

  /* ---- SEO/AEO/GEO explainers ---- */
  .explainer-list { margin-top: 2mm; }
  .explainer { padding: 5mm 0; border-top: 1px solid ${BRAND.divider}; break-inside: avoid; page-break-inside: avoid; }
  .explainer-term { font-size: 15px; font-weight: 700; color: ${BRAND.navy}; margin: 0 0 2mm; }
  .explainer-full { font-size: 11px; font-weight: 500; color: ${BRAND.faint}; }
  .explainer-copy { font-size: 12px; color: ${BRAND.muted}; line-height: 1.6; max-width: 155mm; margin: 0; }

  .callout { margin-top: 8mm; padding: 6mm 7mm; background: ${BRAND.surface}; border-left: 3px solid ${BRAND.red}; break-inside: avoid; page-break-inside: avoid; }
  .callout-copy { font-size: 12.5px; line-height: 1.6; color: ${BRAND.navy}; margin: 0; }

  /* ---- compact AI-visibility score, page 2 ---- */
  .mini-score { display: flex; align-items: baseline; gap: 5mm; margin: 8mm 0; padding-top: 8mm; border-top: 1px solid ${BRAND.divider}; break-inside: avoid; page-break-inside: avoid; }
  .mini-score-value { font-family: 'DM Mono', monospace; font-size: 28px; font-weight: 500; color: ${BRAND.navy}; flex-shrink: 0; }
  .mini-score-max { font-size: 12px; color: ${BRAND.faint}; }
  .mini-score-label { font-size: 11.5px; color: ${BRAND.muted}; line-height: 1.5; }

  /* ---- competitors, page 2 ---- */
  .competitors { margin-top: 8mm; padding-top: 8mm; border-top: 1px solid ${BRAND.divider}; }
  .competitor-row { padding: 4mm 0; break-inside: avoid; page-break-inside: avoid; }
  .competitor-head { display: flex; align-items: baseline; justify-content: space-between; gap: 6mm; }
  .competitor-domain { font-family: 'DM Mono', monospace; font-size: 12px; font-weight: 500; color: ${BRAND.faint}; }
  .competitor-rank { font-size: 9.5px; letter-spacing: 0.03em; color: ${BRAND.faint}; text-align: right; flex-shrink: 0; }
  .competitor-headline { font-size: 13px; font-weight: 600; color: ${BRAND.navy}; line-height: 1.5; margin: 1.5mm 0 0; max-width: 150mm; }
  .competitor-copy { font-size: 11.5px; color: ${BRAND.muted}; line-height: 1.5; margin: 1.5mm 0 0; max-width: 150mm; }

  /* ---- autonomous-agent note, page 3 ---- */
  .agent-note { margin-top: 8mm; padding: 6mm 7mm; background: ${BRAND.surface}; border-left: 3px solid ${BRAND.navy}; break-inside: avoid; page-break-inside: avoid; }
  .agent-copy { font-size: 12px; line-height: 1.6; color: ${BRAND.navy}; margin: 0; }

  /* ---- getting-started lists, page 4 ---- */
  .starter-block { margin-top: 6mm; }
  .starter-list { margin: 0; padding-left: 5mm; }
  .starter-list li { font-size: 12.5px; color: ${BRAND.navy}; line-height: 1.8; }

  /* ---- closing commitment statement, page 4 ---- */
  .commitment { margin-top: 10mm; padding: 7mm 8mm; background: ${BRAND.navy}; border-radius: 3px; break-inside: avoid; page-break-inside: avoid; }
  .commitment .label-small { color: rgba(255,255,255,0.55); margin-bottom: 3mm; }
  .commitment-copy { font-size: 12.5px; line-height: 1.7; color: #fff; margin: 0; max-width: 155mm; }

  .assessment { margin-top: 8mm; padding-top: 8mm; border-top: 1px solid ${BRAND.divider}; }
  .label-small { font-size: 10px; letter-spacing: 0.1em; text-transform: uppercase; color: ${BRAND.faint}; font-weight: 700; margin-bottom: 4mm; }
  .assessment-copy p { font-size: 13.5px; line-height: 1.8; color: ${BRAND.navy}; max-width: 150mm; margin: 0 0 4mm; }
  .assessment-copy strong { color: ${BRAND.navy}; font-weight: 700; }

  /* ---- health score ---- */
  .score-moment { margin: 6mm 0 10mm; break-inside: avoid; page-break-inside: avoid; }
  .score-value { font-family: 'DM Mono', monospace; font-size: 52px; font-weight: 500; color: ${BRAND.navy}; }
  .score-max { font-size: 22px; color: ${BRAND.faint}; }
  .score-status { display: inline-block; margin-left: 6mm; font-size: 11px; letter-spacing: 0.1em; font-weight: 700; vertical-align: middle; }
  .score-bar { width: 130mm; height: 5px; background: ${BRAND.divider}; margin: 8mm 0 6mm; border-radius: 2px; overflow: hidden; }
  .score-bar-fill { height: 100%; background: ${BRAND.navy}; border-radius: 2px; }
  .score-caption { font-size: 12.5px; color: ${BRAND.muted}; line-height: 1.6; max-width: 140mm; }

  /* ---- recommendation rows ---- */
  .rec-list { margin-top: 2mm; }
  .rec-row { display: flex; align-items: flex-start; gap: 6mm; padding: 6mm 0; break-inside: avoid; page-break-inside: avoid; }
  .rec-divider { height: 1px; background: ${BRAND.divider}; }
  .rec-num { font-family: 'DM Mono', monospace; font-size: 20px; color: ${BRAND.faint}; width: 12mm; flex-shrink: 0; }
  .rec-body { flex: 1; }
  .rec-title { font-size: 13.5px; font-weight: 700; color: ${BRAND.navy}; margin: 0 0 2mm; }
  .rec-desc { font-size: 11.5px; color: ${BRAND.muted}; line-height: 1.5; margin: 0; max-width: 120mm; }
  .rec-priority { width: 30mm; flex-shrink: 0; font-size: 9.5px; letter-spacing: 0.06em; font-weight: 700; text-align: right; padding-top: 1mm; }
  .rec-summary { font-size: 10.5px; color: ${BRAND.faint}; margin-top: 6mm; }

  /* ---- roadmap ---- */
  .roadmap { margin-top: 10mm; }
  .roadmap-stage { display: flex; align-items: flex-start; gap: 6mm; break-inside: avoid; page-break-inside: avoid; }
  .roadmap-marker { width: 10mm; height: 10mm; border-radius: 50%; border: 1.5px solid ${BRAND.navy}; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
  .roadmap-marker span { font-family: 'DM Mono', monospace; font-size: 10px; color: ${BRAND.navy}; }
  .roadmap-title { font-size: 14px; font-weight: 700; color: ${BRAND.navy}; margin: 0 0 1mm; }
  .roadmap-copy { font-size: 11.5px; color: ${BRAND.muted}; margin: 0; }
  .roadmap-line { width: 1.5px; height: 8mm; background: ${BRAND.divider}; margin: 1mm 0 1mm 5mm; }

  .closing { margin-top: 20mm; text-align: center; }
  .closing-logo { display: flex; justify-content: center; margin: 0 auto 6mm; }
  .closing-tag { font-size: 10px; color: ${BRAND.faint}; margin: 3mm 0 0; }
`;

export async function renderBaselineReportPdf(html) {
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox', '--disable-dev-shm-usage'] });
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle' });
    return await page.pdf({ format: 'A4', printBackground: true, margin: { top: '0mm', bottom: '0mm', left: '0mm', right: '0mm' } });
  } finally {
    await browser.close();
  }
}
