import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { marked } from 'marked';
import { chromium } from 'playwright';

// PREMIUM CLIENT-FACING BASELINE REPORT PDF.
//
// Replaces the earlier version of this file, which just ran the LLM's
// narrative_md through `marked` and printed it — heading, paragraph,
// heading, bullet list, repeat, at Letter size with no branding. This
// builds a real multi-page A4 document driven directly from the STRUCTURED
// snapshot (kpi_snapshot, issues_snapshot — see agents/lib/baseline-report.js)
// rather than re-parsing the LLM's freeform markdown for the numeric/
// tabular sections, so every number, table and row is exactly what is
// stored, laid out deliberately instead of left to whatever `marked` and
// the browser's default pagination produce.
//
// The one place real LLM prose is used is the Executive Assessment
// paragraph on the Website Snapshot page — extracted verbatim from
// narrative_md's "Where Your Website Stood" section (extractMarkdownSection
// below) — per the explicit instruction to use the existing writing, not
// invented copy, for that one editorial block. Every other caption/sentence
// in this document is a DETERMINISTIC template built from real numbers
// already in the snapshot (see scoreExplanation/auditScopeText/etc.) —
// deliberately not narrative-text-dependent, since narrative_md is
// regenerated by an LLM on every run and its exact wording is not a stable
// thing to build a rendering pipeline around.
//
// Branding: the actual Zunkiree Labs logo (report/assets/zunkireelabs-logo.svg,
// copied byte-for-byte from the live zunkireelabs-web repo's own
// src/assets/images/zunkireelabs-logo.svg — never redrawn or recolored) and
// the real brand palette from that repo's tailwind.config.js: zunkiree red
// #eb1600 as the only accent, navy/near-black #0f172a for primary text,
// slate #64748b for muted text. Typography is the site's own Google Fonts
// pairing, DM Sans (display/body) + DM Mono (statistics) — loaded exactly
// the way the live site loads them.

const __dirname = dirname(fileURLToPath(import.meta.url));
const LOGO_SVG = readFileSync(join(__dirname, 'assets/zunkireelabs-logo.svg'), 'utf8');

const BRAND = {
  red: '#eb1600',
  navy: '#0f172a',
  muted: '#64748b',
  faint: '#94a3b8',
  divider: '#e2e8f0',
  surface: '#f9f7f4',
};

function escapeHtml(s) {
  return String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

const numberFormat = (n) => Number(n ?? 0).toLocaleString('en-US');

// Pulls one `## Heading` section's real text out of the LLM's narrative_md,
// so the Executive Assessment block on page 2 quotes the model's actual
// written words rather than a value re-derived here. Returns '' (never a
// fabricated fallback sentence) when the heading is missing — the caller is
// responsible for handling an empty result honestly.
export function extractMarkdownSection(md, heading) {
  if (!md) return '';
  const re = new RegExp(`^##\\s+${heading.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*$`, 'm');
  const m = re.exec(md);
  if (!m) return '';
  const rest = md.slice(m.index + m[0].length);
  const next = rest.search(/^##\s+/m);
  return (next === -1 ? rest : rest.slice(0, next)).trim();
}

// A short, human title for a recommendation ROW — derived from the real
// `type`/`issue` fields already on the record (never a new fact), the same
// way a person skimming the sentence would summarize it. Falls back to the
// recommendation's own type name, Title Cased, for anything unrecognized —
// never invents a description the data doesn't support.
export function recommendationTitle(item) {
  const issue = String(item.issue || '');
  if (item.type === 'faq') return 'Add FAQ';
  if (item.type === 'landing-page') return 'Generate Landing Page';
  if (item.type === 'schema' || item.type === 'schema-repair') return 'Add Schema Markup';
  if (item.type === 'broken-link-fix') return 'Remove Invalid Citation';
  if (item.type === 'alt-text') return 'Add Image Alt Text';
  if (/comparison|alternatives|best of/i.test(issue)) return 'Add Comparison Content';
  if (/author|byline/i.test(issue)) return 'Add Author/Byline Markup';
  if (/breadcrumb/i.test(issue)) return 'Add Breadcrumbs';
  if (/freshness|last.?updated/i.test(issue)) return 'Add Freshness Signal';
  return String(item.type || 'Recommendation').replace(/[-_]+/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

const PRIORITY_ORDER = { high: 0, medium: 1, low: 2 };
const PRIORITY_LABEL = { high: 'HIGH PRIORITY', medium: 'MEDIUM PRIORITY', low: 'LOW PRIORITY' };
const PRIORITY_COLOR = { high: BRAND.red, medium: BRAND.navy, low: BRAND.muted };

const MAX_RECOMMENDATION_ROWS = 8;

// True when the row's supporting sentence would just restate its own title
// verbatim — real data on Admizz's actual report: the record's `issue` field
// for a faq/landing-page/broken-link-fix recommendation IS already the short
// form ("Add FAQ" / "Add FAQ"), so printing both looked like a bug, not a
// title + description. Ignores trailing punctuation/case only — never
// rewrites either string.
export function descriptionRepeatsTitle(title, issue) {
  const norm = (s) => String(s || '').trim().toLowerCase().replace(/[.\s]+$/, '');
  return norm(title) === norm(issue);
}

// Featured list = the highest-priority REPRESENTATIVE of each distinct issue
// type, not the raw top N by priority. Real data on Admizz's audit: of 217
// open items, the first 8 by priority alone were "Add Author/Byline Markup"
// three times and "Add Comparison Content" twice — genuinely the highest-
// priority items, but a report meant to show the SHAPE of what's missing is
// stronger showing 6-8 distinct problems once each than the same headline
// repeated. Every row shown is still a real record for a real page; this
// only decides which of several equivalent real records represents its type.
export function selectFeaturedRecommendations(items, max) {
  const sorted = [...items].sort((a, b) => (PRIORITY_ORDER[a.priority] ?? 9) - (PRIORITY_ORDER[b.priority] ?? 9));
  const seen = new Set();
  const out = [];
  for (const item of sorted) {
    const key = recommendationTitle(item).toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(item);
    if (out.length >= max) break;
  }
  return out;
}

export function scoreStatusWord(score) {
  if (score < 40) return 'NEEDS ATTENTION';
  if (score < 70) return 'DEVELOPING';
  return 'STRONG';
}

// Deterministic, real-data-grounded caption — see this file's top comment
// for why this is computed rather than pulled from narrative_md.
function scoreExplanation(score) {
  if (score < 40) {
    return 'This score reflects real gaps across technical SEO, content depth and AI-readiness — most of which are addressed by the recommendations on the following pages.';
  }
  if (score < 70) {
    return 'This score reflects a partially optimized site with specific, addressable gaps — the recommendations on the following pages close them.';
  }
  return 'This score reflects a well-optimized site. The recommendations on the following pages are refinements rather than fundamentals.';
}

const AI_STATUS_COLOR = { Missing: BRAND.red, Partial: BRAND.navy, Good: BRAND.muted };

function pageChrome({ eyebrow, sectionNumber, sectionTitle, body, footerNote, siteName, dateLabel, pageNumber }) {
  return `
  <section class="page">
    <header class="page-header">
      <div class="page-header-logo">${LOGO_SVG}</div>
      <div class="page-header-meta">
        <span class="page-header-label">Baseline Report</span>
        <span class="page-header-sub">${escapeHtml(siteName)} · ${escapeHtml(dateLabel)}</span>
      </div>
    </header>
    <div class="page-divider"></div>
    ${sectionNumber ? `
    <div class="section-marker">
      <span class="section-number">${sectionNumber}</span>
      <span class="section-title">${escapeHtml(sectionTitle)}</span>
    </div>` : ''}
    ${eyebrow ? `<p class="eyebrow">${escapeHtml(eyebrow)}</p>` : ''}
    <div class="page-body">${body}</div>
    <footer class="page-footer">
      <div class="page-footer-divider"></div>
      <div class="page-footer-row">
        <span class="page-footer-brand">Zunkiree Labs <span class="page-footer-dim">— AI-Powered Website Growth</span></span>
        <span class="page-footer-page">${pageNumber}</span>
      </div>
      ${footerNote ? `<p class="page-footer-note">${footerNote}</p>` : ''}
    </footer>
  </section>`;
}

function coverPage({ siteName, dateLabel }) {
  return `
  <section class="page cover-page">
    <div class="cover-motif" aria-hidden="true">
      <svg width="420" height="420" viewBox="0 0 420 420" fill="none">
        <line x1="0" y1="60" x2="420" y2="60" stroke="${BRAND.red}" stroke-width="1" opacity="0.08"/>
        <line x1="0" y1="140" x2="420" y2="140" stroke="${BRAND.navy}" stroke-width="1" opacity="0.06"/>
        <line x1="60" y1="0" x2="60" y2="420" stroke="${BRAND.red}" stroke-width="1" opacity="0.06"/>
        <circle cx="380" cy="380" r="3" fill="${BRAND.red}" opacity="0.35"/>
        <circle cx="360" cy="340" r="2" fill="${BRAND.navy}" opacity="0.2"/>
        <circle cx="400" cy="320" r="1.5" fill="${BRAND.navy}" opacity="0.2"/>
      </svg>
    </div>
    <div class="cover-logo">${LOGO_SVG}</div>
    <p class="cover-eyebrow">AI-Powered Website Growth</p>
    <div class="cover-title-block">
      <h1 class="cover-title">Baseline<br/>Report</h1>
      <p class="cover-client">${escapeHtml(siteName)}</p>
      <p class="cover-date">${escapeHtml(dateLabel).toUpperCase()}</p>
    </div>
    <div class="cover-rule"></div>
    <p class="cover-statement">Your starting point for measuring website growth, search visibility, and optimization progress.</p>
  </section>`;
}

function metricBlock(value, label) {
  return `<div class="metric"><span class="metric-value">${escapeHtml(value)}</span><span class="metric-label">${escapeHtml(label)}</span></div>`;
}

function snapshotPage({ kpi, execAssessmentHtml, siteName, dateLabel }) {
  const body = `
    <div class="metric-row">
      ${metricBlock(numberFormat(kpi.clicks), 'Clicks')}
      ${metricBlock(numberFormat(kpi.impressions), 'Impressions')}
      ${metricBlock(numberFormat(kpi.sessions), 'Sessions')}
      ${metricBlock(numberFormat(kpi.users), 'Unique Users')}
    </div>
    <div class="metric-row metric-row-secondary">
      ${metricBlock(`${kpi.daysOfHistory} Days`, 'Data Available')}
      ${metricBlock(`${kpi.healthScore} / 100`, 'Health Score')}
    </div>
    <div class="assessment">
      <p class="label-small">Executive Assessment</p>
      <div class="assessment-copy">${execAssessmentHtml || '<p>Insufficient history to assess yet.</p>'}</div>
    </div>`;
  return pageChrome({
    sectionNumber: '01', sectionTitle: 'Website Snapshot',
    eyebrow: null,
    body: `<p class="section-intro">A quick overview of your website's current performance and data availability.</p>${body}`,
    siteName, dateLabel, pageNumber: 2,
  });
}

function healthPage({ kpi, auditFindings, siteName, dateLabel }) {
  const score = kpi.healthScore ?? 0;
  const status = scoreStatusWord(score);
  const findingsCount = auditFindings ? numberFormat(auditFindings.total) : null;
  const findingsQualifier = auditFindings?.truncated ? 'at least ' : '';
  const body = `
    <div class="score-moment">
      <span class="score-value">${score} <span class="score-max">/ 100</span></span>
      <span class="score-status" style="color:${status === 'NEEDS ATTENTION' ? BRAND.red : BRAND.navy}">${status}</span>
      <div class="score-bar"><div class="score-bar-fill" style="width:${Math.max(2, Math.min(100, score))}%"></div></div>
      <p class="score-caption">${scoreExplanation(score)}</p>
    </div>
    ${auditFindings ? `
    <div class="audit-scope">
      <div class="audit-scope-stat">
        ${findingsQualifier ? `<span class="audit-scope-qualifier">At Least</span>` : ''}
        <span class="audit-scope-value">${findingsCount}</span>
        <span class="audit-scope-label">Total Findings</span>
      </div>
      <p class="audit-scope-copy">We completed a full-site audit across ${numberFormat(auditFindings.pagesAffected)} pages, which revealed ${findingsQualifier}${findingsCount} findings related to the overall health and optimization of your website. The most affected pages and issues are broken down on the following pages.</p>
    </div>` : ''}`;
  return pageChrome({
    sectionNumber: '02', sectionTitle: 'Website Health',
    body, siteName, dateLabel, pageNumber: 3,
  });
}

function aiVisibilityPage({ aiVisibility, siteName, dateLabel }) {
  if (!aiVisibility?.available) {
    return pageChrome({
      sectionNumber: '03', sectionTitle: 'How AI Search Engines See You',
      body: '<p class="section-intro">This measurement has not run yet for your site — it will appear in a future report.</p>',
      siteName, dateLabel, pageNumber: 4,
    });
  }
  const worst = aiVisibility.categories[0];
  const rows = aiVisibility.categories.map((c) => `
    <div class="ai-row">
      <span class="ai-row-name">${escapeHtml(c.category)}</span>
      <span class="ai-row-score">${c.score}</span>
      <span class="ai-row-status" style="color:${AI_STATUS_COLOR[c.status] || BRAND.navy}">${c.status.toUpperCase()}</span>
    </div>`).join('');
  const body = `
    <div class="score-moment">
      <span class="score-value">${aiVisibility.overall} <span class="score-max">/ 100</span></span>
      <span class="score-status" style="color:${BRAND.muted}">AI VISIBILITY SCORE</span>
    </div>
    <div class="ai-table">
      <div class="ai-row ai-row-head"><span class="ai-row-name">Area</span><span class="ai-row-score">Score</span><span class="ai-row-status">Status</span></div>
      ${rows}
    </div>
    <p class="section-intro" style="margin-top:8mm;">AI assistants and search engines increasingly answer questions directly instead of sending a click. The categories above measure whether ${escapeHtml(siteName)} can be read, understood and cited by them. The most significant gap today is ${escapeHtml(worst.category).toLowerCase()} at ${worst.score}/100.</p>`;
  return pageChrome({
    sectionNumber: '03', sectionTitle: 'How AI Search Engines See You',
    body, siteName, dateLabel, pageNumber: 4,
  });
}

function issuesPage({ openRecommendations, siteName, dateLabel }) {
  const items = selectFeaturedRecommendations(openRecommendations?.items || [], MAX_RECOMMENDATION_ROWS);
  const rows = items.map((item, i) => {
    const num = String(i + 1).padStart(2, '0');
    const title = recommendationTitle(item);
    const titleHtml = item.page
      ? `<a class="rec-link" href="${escapeHtml(item.page)}">${escapeHtml(title)}</a>`
      : escapeHtml(title);
    const descHtml = descriptionRepeatsTitle(title, item.issue) ? '' : `<p class="rec-desc">${escapeHtml(item.issue)}</p>`;
    return `
    <div class="rec-row">
      <span class="rec-num">${num}</span>
      <div class="rec-body">
        <p class="rec-title">${titleHtml}</p>
        ${descHtml}
      </div>
      <span class="rec-priority" style="color:${PRIORITY_COLOR[item.priority] || BRAND.muted}">${PRIORITY_LABEL[item.priority] || item.priority?.toUpperCase() || ''}</span>
    </div>`;
  }).join('<div class="rec-divider"></div>');

  const total = openRecommendations?.total || items.length;
  const summaryNote = total > items.length
    ? `Showing ${items.length} representative issue${items.length === 1 ? '' : 's'} across ${numberFormat(total)} total open recommendations, prioritized by impact.`
    : `All ${numberFormat(total)} open recommendations shown.`;

  const body = `
    <p class="section-intro">In our preliminary assessment of your website, we identified several opportunities for enhancement, categorized by priority:</p>
    <div class="rec-list">${rows}</div>
    <p class="rec-summary">${summaryNote}</p>`;
  return pageChrome({
    sectionNumber: '04', sectionTitle: 'Issues We Found',
    body, siteName, dateLabel, pageNumber: 5,
  });
}

const ROADMAP_STAGES = [
  { n: '01', title: 'Baseline', copy: 'Current website performance, measured today.' },
  { n: '02', title: 'Optimization', copy: 'Address the priority findings identified above.' },
  { n: '03', title: 'Milestone Report', copy: 'Measure progress against this baseline.' },
  { n: '04', title: 'Growth', copy: 'Compare real improvements over time.' },
];

function roadmapPage({ siteName, dateLabel }) {
  const stages = ROADMAP_STAGES.map((s, i) => `
    <div class="roadmap-stage">
      <div class="roadmap-marker"><span>${s.n}</span></div>
      <div class="roadmap-text">
        <p class="roadmap-title">${escapeHtml(s.title)}</p>
        <p class="roadmap-copy">${escapeHtml(s.copy)}</p>
      </div>
    </div>${i < ROADMAP_STAGES.length - 1 ? '<div class="roadmap-line"></div>' : ''}`).join('');

  const body = `
    <p class="section-intro">This report establishes the baseline. Future reports will measure progress against it.</p>
    <div class="roadmap">${stages}</div>
    <div class="closing">
      <div class="cover-logo closing-logo">${LOGO_SVG}</div>
      <p class="closing-brand">Zunkiree Labs</p>
      <p class="closing-tag">AI-Powered Website Growth</p>
    </div>`;
  return pageChrome({
    sectionNumber: '05', sectionTitle: 'What Happens Next',
    body, siteName, dateLabel, pageNumber: 6,
  });
}

// `report` is a raw baseline_reports row (kpi_snapshot/issues_snapshot/
// narrative_md/generated_at, see store/baseline-reports.js), `site` a raw
// sites row.
export function renderBaselineReportHtml(report, site) {
  const kpi = report.kpi_snapshot || {};
  const issues = report.issues_snapshot || {};
  const dateLabel = new Date(report.generated_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: '2-digit' });
  const execAssessmentHtml = marked.parse(extractMarkdownSection(report.narrative_md, 'Where Your Website Stood') || '');

  const pages = [
    coverPage({ siteName: site.name, dateLabel }),
    snapshotPage({ kpi, execAssessmentHtml, siteName: site.name, dateLabel }),
    healthPage({ kpi, auditFindings: issues.auditFindings, siteName: site.name, dateLabel }),
    aiVisibilityPage({ aiVisibility: issues.aiVisibility, siteName: site.name, dateLabel }),
    issuesPage({ openRecommendations: issues.openRecommendations, siteName: site.name, dateLabel }),
    roadmapPage({ siteName: site.name, dateLabel }),
  ].join('\n');

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>${escapeHtml(site.name)} — Baseline Report</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,600;9..40,700&display=swap" rel="stylesheet">
<style>${REPORT_CSS}</style>
</head>
<body>
${pages}
</body>
</html>`;
}

const REPORT_CSS = `
  @page { size: A4; margin: 0; }
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; background: ${BRAND.surface}; }
  body { font-family: 'DM Sans', -apple-system, 'Helvetica Neue', Arial, sans-serif; color: ${BRAND.navy}; }
  .page {
    width: 210mm; min-height: 297mm; position: relative;
    background: #fff; padding: 20mm 18mm 16mm; margin: 0 auto;
    display: flex; flex-direction: column;
    page-break-after: always; break-after: page;
    box-shadow: 0 1px 3px rgba(15,23,42,0.08), 0 8px 24px rgba(15,23,42,0.06);
  }
  .page:last-child { page-break-after: auto; }
  @media print { .page { box-shadow: none; margin: 0; } body { background: #fff; } }

  /* ---- shared header/footer ---- */
  .page-header { display: flex; align-items: center; justify-content: space-between; }
  .page-header-logo svg { height: 16px; width: auto; display: block; }
  .page-header-meta { text-align: right; }
  .page-header-label { display: block; font-size: 9px; letter-spacing: 0.12em; text-transform: uppercase; color: ${BRAND.faint}; font-weight: 600; }
  .page-header-sub { display: block; font-size: 9px; color: ${BRAND.muted}; margin-top: 2px; }
  .page-divider { height: 1px; background: ${BRAND.divider}; margin: 6mm 0 8mm; }

  .section-marker { display: flex; align-items: baseline; gap: 4mm; margin-bottom: 4mm; }
  .section-number { font-family: 'DM Mono', monospace; font-size: 12px; color: ${BRAND.faint}; }
  .section-title { font-size: 11px; letter-spacing: 0.1em; text-transform: uppercase; font-weight: 700; color: ${BRAND.navy}; }
  .eyebrow { font-size: 10px; letter-spacing: 0.1em; text-transform: uppercase; color: ${BRAND.faint}; }
  .section-intro { font-size: 12.5px; color: ${BRAND.muted}; line-height: 1.6; max-width: 150mm; margin: 0 0 8mm; }

  /* Vertically centers each page's content block(s) as a group in the space
     between header and footer, instead of clustering at the top and leaving
     a large dead zone above the footer on shorter pages (cover, health,
     roadmap) — the exact "awkward empty area" this report must avoid. Packs
     multiple direct children together with no extra gap between them
     (justify-content: center's default), so a page with several stacked
     blocks (metrics + assessment) still reads as one composed unit. */
  .page-body { flex: 1; display: flex; flex-direction: column; justify-content: center; }

  .page-footer { margin-top: auto; padding-top: 6mm; }
  .page-footer-divider { height: 1px; background: ${BRAND.divider}; margin-bottom: 3mm; }
  .page-footer-row { display: flex; align-items: center; justify-content: space-between; }
  .page-footer-brand { font-size: 9px; color: ${BRAND.navy}; font-weight: 600; }
  .page-footer-dim { color: ${BRAND.faint}; font-weight: 400; }
  .page-footer-page { font-family: 'DM Mono', monospace; font-size: 9px; color: ${BRAND.faint}; }
  .page-footer-note { font-size: 8.5px; color: ${BRAND.faint}; margin: 2mm 0 0; }

  /* ---- cover ---- */
  .cover-page { justify-content: flex-start; }
  .cover-motif { position: absolute; top: 0; right: 0; pointer-events: none; }
  .cover-logo svg { height: 22px; width: auto; }
  .cover-eyebrow { font-size: 11px; letter-spacing: 0.14em; text-transform: uppercase; color: ${BRAND.faint}; font-weight: 600; margin: 14mm 0 0; }
  .cover-title-block { margin-top: 60mm; }
  .cover-title { font-size: 56px; line-height: 1.02; font-weight: 700; letter-spacing: -0.01em; margin: 0 0 10mm; color: ${BRAND.navy}; }
  .cover-client { font-size: 20px; font-weight: 500; color: ${BRAND.navy}; margin: 0 0 2mm; }
  .cover-date { font-size: 11px; letter-spacing: 0.1em; color: ${BRAND.faint}; margin: 0; }
  .cover-rule { width: 32px; height: 3px; background: ${BRAND.red}; margin: 12mm 0 6mm; }
  .cover-statement { font-size: 14px; line-height: 1.6; color: ${BRAND.muted}; max-width: 100mm; }

  /* ---- metrics ---- */
  .metric-row { display: flex; margin: 4mm 0; }
  .metric-row-secondary { margin-top: 2mm; }
  .metric { flex: 1; padding: 0 6mm; border-left: 1px solid ${BRAND.divider}; }
  .metric:first-child { padding-left: 0; border-left: none; }
  .metric-value { display: block; font-family: 'DM Mono', monospace; font-size: 30px; font-weight: 500; color: ${BRAND.navy}; }
  .metric-label { display: block; font-size: 9px; letter-spacing: 0.08em; text-transform: uppercase; color: ${BRAND.faint}; margin-top: 2mm; }

  .assessment { margin-top: 12mm; }
  .label-small { font-size: 10px; letter-spacing: 0.1em; text-transform: uppercase; color: ${BRAND.faint}; font-weight: 700; margin-bottom: 4mm; }
  .assessment-copy p { font-size: 13.5px; line-height: 1.8; color: ${BRAND.navy}; max-width: 150mm; margin: 0 0 4mm; }
  .assessment-copy strong { color: ${BRAND.navy}; font-weight: 700; }

  /* ---- health score ---- */
  .score-moment { margin: 6mm 0 10mm; break-inside: avoid; page-break-inside: avoid; }
  .score-value { font-family: 'DM Mono', monospace; font-size: 52px; font-weight: 500; color: ${BRAND.navy}; }
  .score-max { font-size: 22px; color: ${BRAND.faint}; }
  .score-status { display: inline-block; margin-left: 6mm; font-size: 11px; letter-spacing: 0.1em; font-weight: 700; vertical-align: middle; }
  .score-bar { width: 130mm; height: 5px; background: ${BRAND.divider}; margin: 8mm 0 6mm; border-radius: 2px; overflow: hidden; }
  .score-bar-fill { height: 100%; background: ${BRAND.navy}; border-radius: 2px; }
  .score-caption { font-size: 12.5px; color: ${BRAND.muted}; line-height: 1.6; max-width: 140mm; }

  .audit-scope { margin-top: 14mm; padding-top: 10mm; border-top: 1px solid ${BRAND.divider}; }
  .audit-scope-qualifier { display: block; font-size: 10px; letter-spacing: 0.1em; text-transform: uppercase; color: ${BRAND.faint}; font-weight: 700; margin-bottom: 1mm; }
  .audit-scope-value { font-family: 'DM Mono', monospace; font-size: 44px; font-weight: 500; color: ${BRAND.red}; }
  .audit-scope-label { display: block; font-size: 10px; letter-spacing: 0.1em; text-transform: uppercase; color: ${BRAND.faint}; margin-top: 1mm; }
  .audit-scope-copy { font-size: 12.5px; color: ${BRAND.muted}; line-height: 1.6; max-width: 140mm; margin-top: 6mm; }

  /* ---- AI visibility table ---- */
  .ai-table { margin-top: 6mm; }
  .ai-row { display: flex; align-items: center; padding: 4mm 0; border-bottom: 1px solid ${BRAND.divider}; break-inside: avoid; page-break-inside: avoid; }
  .ai-row-head { font-size: 9px; letter-spacing: 0.08em; text-transform: uppercase; color: ${BRAND.faint}; font-weight: 700; border-bottom: 1px solid ${BRAND.navy}; }
  .ai-row-name { flex: 1; font-size: 12.5px; color: ${BRAND.navy}; }
  .ai-row-score { width: 24mm; font-family: 'DM Mono', monospace; font-size: 13px; color: ${BRAND.navy}; }
  .ai-row-status { width: 34mm; font-size: 10px; letter-spacing: 0.06em; font-weight: 700; text-align: right; }

  /* ---- recommendation rows ---- */
  .rec-list { margin-top: 2mm; }
  .rec-row { display: flex; align-items: flex-start; gap: 6mm; padding: 6mm 0; break-inside: avoid; page-break-inside: avoid; }
  .rec-divider { height: 1px; background: ${BRAND.divider}; }
  .rec-num { font-family: 'DM Mono', monospace; font-size: 20px; color: ${BRAND.faint}; width: 12mm; flex-shrink: 0; }
  .rec-body { flex: 1; }
  .rec-title { font-size: 13.5px; font-weight: 700; color: ${BRAND.navy}; margin: 0 0 2mm; }
  .rec-link { color: ${BRAND.navy}; text-decoration: none; border-bottom: 1px solid ${BRAND.red}; }
  .rec-desc { font-size: 11.5px; color: ${BRAND.muted}; line-height: 1.5; margin: 0; max-width: 120mm; }
  .rec-priority { width: 30mm; flex-shrink: 0; font-size: 9.5px; letter-spacing: 0.06em; font-weight: 700; text-align: right; padding-top: 1mm; }
  .rec-summary { font-size: 10.5px; color: ${BRAND.faint}; margin-top: 6mm; }

  /* ---- roadmap ---- */
  .roadmap { margin-top: 10mm; }
  .roadmap-stage { display: flex; align-items: flex-start; gap: 6mm; break-inside: avoid; page-break-inside: avoid; }
  .roadmap-marker { width: 10mm; height: 10mm; border-radius: 50%; border: 1.5px solid ${BRAND.navy}; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
  .roadmap-marker span { font-family: 'DM Mono', monospace; font-size: 10px; color: ${BRAND.navy}; }
  .roadmap-title { font-size: 14px; font-weight: 700; color: ${BRAND.navy}; margin: 0 0 1mm; }
  .roadmap-copy { font-size: 11.5px; color: ${BRAND.muted}; margin: 0; }
  .roadmap-line { width: 1.5px; height: 8mm; background: ${BRAND.divider}; margin: 1mm 0 1mm 5mm; }

  .closing { margin-top: 20mm; text-align: center; }
  .closing-logo svg { height: 18px; width: auto; margin: 0 auto 6mm; display: block; }
  .closing-brand { font-size: 13px; font-weight: 700; color: ${BRAND.navy}; margin: 0; }
  .closing-tag { font-size: 10px; color: ${BRAND.faint}; margin: 1mm 0 0; }
`;

export async function renderBaselineReportPdf(html) {
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox', '--disable-dev-shm-usage'] });
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle' });
    return await page.pdf({ format: 'A4', printBackground: true, margin: { top: '0mm', bottom: '0mm', left: '0mm', right: '0mm' } });
  } finally {
    await browser.close();
  }
}
