-- Persist the narrative prose already generated by the daily/weekly/monthly
-- Google Doc reports so the dashboard's inline Reports page can show it
-- without a duplicate LLM call. Date-ish columns are TEXT (YYYY-MM-DD /
-- YYYY-MM), matching how dates are passed as plain strings everywhere else
-- in this codebase, so exact-match comparisons don't need date parsing.
ALTER TABLE sites ADD COLUMN IF NOT EXISTS daily_report_narrative TEXT;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS daily_report_narrative_date TEXT;

ALTER TABLE sites ADD COLUMN IF NOT EXISTS weekly_report_narrative TEXT;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS weekly_report_narrative_start TEXT;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS weekly_report_narrative_end TEXT;

ALTER TABLE sites ADD COLUMN IF NOT EXISTS monthly_report_narrative TEXT;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS monthly_report_narrative_ym TEXT;
