-- Supplementary keyword/AEO narrative — generated by server/agents/keyword-narrative.js
-- every 14 days (same cadence as agents/clustering.py, see server/cron.js), independent
-- of the Python executive-summary pipeline in data-analyst-agent/. Synthesizes
-- keyword_gaps + keyword_clusters + site_profiles + the latest ai-visibility agent_runs
-- row into a short narrative. Append-only per run, same convention as keyword_clusters
-- (079_keyword_clusters.sql) — callers read the latest row via ORDER BY created_at DESC LIMIT 1.
CREATE TABLE IF NOT EXISTS keyword_narratives (
  id          SERIAL PRIMARY KEY,
  site_id     INT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  narrative   TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_keyword_narratives_lookup ON keyword_narratives (site_id, created_at DESC);
