"""Proactive Investigation Reasoning (Phase 3) — makes the existing
grounded LLM summary generation from app/insights/recommendations.py
(previously only on-demand: generate_executive_summary,
generate_dashboard_executive_summary) run automatically once per
investigation during the nightly pipeline, and PERSISTS the result onto
the investigations row instead of regenerating it stateless on every page
view. Reuses the same call_llm plumbing and anti-fabrication discipline as
those two functions — no new LLM infrastructure, just a new caller and a
tool schema covering the fields the existing hero-summary tool doesn't
already produce. root_cause_text/evidence/forecast_outlook are reused
as-is for "likely causes"/"supporting evidence"/"forecast outlook" rather
than re-generated by a second LLM call — see Investigation's own docstring
in app/db/models.py.

Generates ONCE per investigation (executive_summary IS NULL is the retry
condition, same idempotent-once-until-success contract as every other
Phase 2 engine's already_scored-style guard) — an open investigation whose
evidence later changes keeps its original reasoning rather than being
re-narrated every night, which would mean duplicate model execution
(Step 13) for an investigation that hasn't reached a new milestone."""
import json

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.agent.narrator import call_llm
from app.db.models import Client, Investigation, MetricCatalog, Opportunity
from app.db.session import SessionLocal

REASONING_SYSTEM_PROMPT = (
    "You are generating persisted analyst reasoning for one Investigation in an AI growth intelligence "
    "platform. You are given the investigation's metric, dimension, severity, status, evidence, forecast "
    "outlook (if any), root cause narrative (if computed), business impact/opportunity data (if computed), "
    "and confidence. Call submit_reasoning with five distinct write-ups for different audiences and purposes: "
    "an executive summary (2-3 plain-English sentences for a non-technical stakeholder), a technical summary "
    "(the precise metric/dimension/statistical evidence, for an analyst), a business summary (what this means "
    "for the client's business, grounded in business_impact if present), a risk assessment (what happens if "
    "nothing is done, grounded only in the forecast/evidence given), and a list of what evidence is still "
    "missing that would make this investigation more conclusive (e.g. 'root cause analysis has not run yet', "
    "'no business value configuration on this client', 'forecast not yet available for this metric') — return "
    "an empty list only when every one of evidence/root_cause_text/forecast_outlook/business_impact you were "
    "given is actually present, not absent.\n\n"
    "Never invent a fact, cause, number, or forecast beyond what's given in the input; when a field you'd need "
    "is null or absent, say so plainly in the relevant summary and list it under missing evidence rather than "
    "guessing or silently omitting the gap."
)

REASONING_TOOL = {
    "name": "submit_reasoning",
    "description": "Submit the five persisted reasoning fields for this investigation.",
    "input_schema": {
        "type": "object",
        "properties": {
            "executive_summary": {
                "type": "string",
                "description": "2-3 plain-English sentences for a non-technical stakeholder.",
            },
            "technical_summary": {
                "type": "string",
                "description": "The precise metric/dimension/statistical evidence, for an analyst.",
            },
            "business_summary": {
                "type": "string",
                "description": "What this means for the client's business, grounded in business_impact if present, or state plainly if not computable.",
            },
            "risk_assessment": {
                "type": "string",
                "description": "What happens if nothing is done, grounded only in the forecast/evidence given.",
            },
            "missing_evidence": {
                "type": "array", "items": {"type": "string"},
                "description": "What evidence is still missing that would make this investigation more conclusive; empty array only if every relevant field was actually present.",
            },
        },
        "required": [
            "executive_summary", "technical_summary", "business_summary",
            "risk_assessment", "missing_evidence",
        ],
    },
}


async def run_investigation_reasoning() -> None:
    async with SessionLocal() as session:
        clients = (await session.execute(select(Client).where(Client.status == "active"))).scalars().all()

    for client in clients:
        async with SessionLocal() as session:
            investigations = (
                await session.execute(
                    select(Investigation).where(
                        Investigation.client_id == client.id, Investigation.executive_summary.is_(None),
                    )
                )
            ).scalars().all()
            catalog_by_key = {m.metric_key: m for m in (await session.execute(select(MetricCatalog))).scalars().all()}
            for investigation in investigations:
                await _generate(session, investigation, catalog_by_key.get(investigation.metric_key))
            await session.commit()


async def _generate(session: AsyncSession, investigation: Investigation, metric: MetricCatalog | None) -> None:
    opportunity = (
        await session.execute(select(Opportunity).where(Opportunity.investigation_id == investigation.id))
    ).scalar_one_or_none()

    business_impact_payload = None
    if opportunity is not None and opportunity.forecast_gain is not None:
        business_impact_payload = {
            "forecast_gain": opportunity.forecast_gain,
            "business_impact": float(opportunity.business_impact) if opportunity.business_impact is not None else None,
            "business_impact_currency": opportunity.business_impact_currency,
            "opportunity_score": float(opportunity.opportunity_score) if opportunity.opportunity_score is not None else None,
        }

    payload = {
        "metric": metric.display_name if metric else investigation.metric_key,
        "dimension_type": investigation.dimension_type, "dimension_value": investigation.dimension_value,
        "insight_type": investigation.insight_type, "severity": investigation.severity,
        "status": investigation.status, "evidence": investigation.evidence,
        "forecast_outlook": investigation.forecast_outlook, "root_cause_text": investigation.root_cause_text,
        "confidence": float(investigation.confidence) if investigation.confidence is not None else None,
        "business_impact": business_impact_payload,
    }

    try:
        response = await call_llm(
            messages=[{"role": "user", "content": json.dumps(payload, default=str)}],
            tools=[REASONING_TOOL], tool_choice={"type": "tool", "name": "submit_reasoning"},
            system=REASONING_SYSTEM_PROMPT,
        )
    except Exception:
        # Leave every field null — next night's run will retry (same
        # discipline as Recommendation.narration_status='pending' elsewhere
        # in this codebase). Never a partial or fabricated write.
        return

    for block in response.content:
        if block.type == "tool_use" and block.name == "submit_reasoning":
            fields = block.input
            investigation.executive_summary = fields.get("executive_summary")
            investigation.technical_summary = fields.get("technical_summary")
            investigation.business_summary = fields.get("business_summary")
            investigation.risk_assessment = fields.get("risk_assessment")
            investigation.missing_evidence = fields.get("missing_evidence") or []
            return
